function run_checks
%RUN_CHECKS Deterministic numerical and interpretation checks for P08.

baseline = model();
assert(baseline.clockErrorBoundUs == 20 && ...
    baseline.activationLeadUs == 1500 && ...
    baseline.distributionDelayScale == 1 && ...
    baseline.allOrNothingActivation, ...
    'P08 defaults changed.');
assert(isequal(baseline.clockOffsetUs,[-20 10 20 -10]) && ...
    baseline.maximumPairwiseClockOffsetUs == 40, ...
    'Baseline residual-clock fixture changed.');
assert(isequal(baseline.versionOnePhaseUs,[0 250 750 500]) && ...
    isequal(baseline.versionTwoPhaseUs,[0 250 500 750]) && ...
    baseline.cyclePeriodUs == 1000 && ...
    baseline.actionDurationUs == 160 && ...
    baseline.nominalGuardUs == 90 && ...
    baseline.scheduleUtilization == 0.64, ...
    'Baseline schedule maps or cycle dimensions changed.');
assert(isequal(baseline.distributionArrivalTrueTimeUs, ...
        [180 420 760 1120]) && ...
    isequal(baseline.scheduleValidationUs,[80 80 120 100]) && ...
    isequal(baseline.scheduleReadyTrueTimeUs,[260 500 880 1220]) && ...
    isequal(baseline.scheduleReadyLocalTimeUs,[240 510 900 1210]), ...
    'Baseline schedule distribution or staging times changed.');
assert(isequal(baseline.nodeActivationTrueTimeUs, ...
        [1520 1490 1480 1510]) && ...
    isequal(baseline.activationSlackUs,[1260 990 600 290]) && ...
    baseline.minimumActivationSlackUs == 290 && ...
    baseline.requiredActivationLeadUs == 1210 && ...
    baseline.maximumActivationLatenessUs == 0, ...
    'Baseline activation times or readiness slack changed.');
assert(all(baseline.nodeReadyAtActivation) && ...
    baseline.readyNodeCount == 4 && baseline.lateNodeCount == 0 && ...
    baseline.allNodesReady && ...
    baseline.newVersionSelectedForAllNodes && ...
    ~baseline.oldVersionRetainedForAllNodes && ...
    ~baseline.partialNewVersionSelected && ...
    ~baseline.newVersionSelectionWithheld && ...
    isequal(baseline.activeScheduleVersion,[2 2 2 2]), ...
    'Baseline coherent version activation changed.');
assert(isequal(baseline.selectedPhaseUs,[0 250 500 750]) && ...
    isequal(baseline.scheduledActionLocalTimeUs, ...
        [1500 1750 2000 2250]) && ...
    isequal(baseline.actionStartTrueTimeUs, ...
        [1520 1740 1980 2260]) && ...
    isequal(baseline.actionEndTrueTimeUs, ...
        [1680 1900 2140 2420]) && ...
    isequal(baseline.actionStartErrorUs,[20 -10 -20 10]) && ...
    isequal(baseline.actionStartRelativeToActivationUs, ...
        [20 240 480 760]), ...
    'Baseline local-to-true action conversion changed.');
assert(isequal(baseline.orderedNodeIndex,[1 2 3 4]) && ...
    isequal(baseline.nextOrderedNodeIndex,[2 3 4 1]) && ...
    isequal(baseline.separationToNextActionUs,[60 80 120 100]) && ...
    baseline.minimumSeparationUs == 60 && ...
    baseline.maximumOverlapUs == 0 && baseline.totalOverlapUs == 0 && ...
    baseline.totalNonoverlapIdleUs == 360 && ...
    baseline.collisionCount == 0 && ~baseline.unsafeOverlapDetected, ...
    'Baseline sorted cyclic interval arithmetic changed.');
assert(baseline.configurationCoherent && ...
    baseline.activeVersionCount == 1 && ...
    baseline.coherentGuaranteedMinSeparationUs == 50 && ...
    baseline.coherentTimingBoundApplicable && ...
    baseline.coherentTimingBoundSatisfiedByActual && ...
    baseline.coherentTimingGuaranteeNonnegative && ...
    strcmp(baseline.scheduleState,'new-schedule-selected'), ...
    'Baseline coherence or guard-bound classification changed.');

repeated = model(20,1500,1,true);
assert(isequal(repeated.clockOffsetUs,baseline.clockOffsetUs) && ...
    isequal(repeated.scheduleReadyLocalTimeUs, ...
        baseline.scheduleReadyLocalTimeUs) && ...
    isequal(repeated.activeScheduleVersion, ...
        baseline.activeScheduleVersion) && ...
    isequal(repeated.actionStartTrueTimeUs, ...
        baseline.actionStartTrueTimeUs) && ...
    isequal(repeated.separationToNextActionUs, ...
        baseline.separationToNextActionUs), ...
    'Identical inputs must reproduce every schedule output.');

shifted = model(20,2000,1,true);
assert(isequal(shifted.actionStartTrueTimeUs, ...
        baseline.actionStartTrueTimeUs + 500) && ...
    isequal(shifted.actionEndTrueTimeUs, ...
        baseline.actionEndTrueTimeUs + 500) && ...
    isequal(shifted.activationSlackUs,baseline.activationSlackUs + 500) && ...
    isequal(shifted.separationToNextActionUs, ...
        baseline.separationToNextActionUs) && ...
    isequal(shifted.activeScheduleVersion, ...
        baseline.activeScheduleVersion), ...
    'A common activation shift must translate actions without changing gaps.');

typed = model(uint16(20),uint16(1500),uint8(1),uint8(1));
assert(isequal(typed.scheduleReadyLocalTimeUs, ...
        baseline.scheduleReadyLocalTimeUs) && ...
    isequal(typed.actionStartTrueTimeUs, ...
        baseline.actionStartTrueTimeUs) && ...
    typed.allOrNothingActivation, ...
    'Accepted integer classes must normalize to baseline arithmetic.');

fractional = model(2.5,1500.5,0.5,true);
assert(isequal(fractional.clockOffsetUs,[-2.5 1.25 2.5 -1.25]) && ...
    isequal(fractional.scheduleReadyTrueTimeUs,[170 290 500 660]) && ...
    isequal(fractional.scheduleReadyLocalTimeUs, ...
        [167.5 291.25 502.5 658.75]) && ...
    isequal(fractional.actionStartErrorUs,[2.5 -1.25 -2.5 1.25]) && ...
    all(isfinite(fractional.actionStartTrueTimeUs)), ...
    'Finite fractional inputs must retain transparent arithmetic.');

clockErrorBoundsUs = [0 20 40];
expectedClockOffsetsUs = [0 20 40];
expectedClockMinimumSeparationUs = [90 60 30];
expectedClockGuaranteedSeparationUs = [90 50 10];
expectedPairwiseOffsetUs = [0 40 80];
for index = 1:numel(clockErrorBoundsUs)
    swept = model(clockErrorBoundsUs(index),1500,1,true);
    assert(max(abs(swept.actionStartErrorUs)) == ...
            expectedClockOffsetsUs(index) && ...
        swept.minimumSeparationUs == ...
            expectedClockMinimumSeparationUs(index) && ...
        swept.coherentGuaranteedMinSeparationUs == ...
            expectedClockGuaranteedSeparationUs(index) && ...
        swept.maximumPairwiseClockOffsetUs == ...
            expectedPairwiseOffsetUs(index), ...
        'Clock-error sweep metrics changed.');
    assert(swept.configurationCoherent && ...
        swept.coherentTimingBoundSatisfiedByActual && ...
        swept.collisionCount == 0 && swept.readyNodeCount == 4, ...
        'Clock-error sweep must keep readiness and version coherent.');
end

zeroClockError = model(0,1500,1,true);
assert(all(zeroClockError.clockOffsetUs == 0) && ...
    isequal(zeroClockError.actionStartTrueTimeUs - ...
        zeroClockError.activationLeadUs,[0 250 500 750]) && ...
    isequal(zeroClockError.separationToNextActionUs,[90 90 90 90]) && ...
    zeroClockError.minimumSeparationUs == zeroClockError.nominalGuardUs, ...
    'Zero clock error must recover the nominal slot map exactly.');

guaranteeBoundary = model(45,1500,1,true);
assert(guaranteeBoundary.coherentGuaranteedMinSeparationUs == 0 && ...
    guaranteeBoundary.coherentTimingGuaranteeNonnegative && ...
    guaranteeBoundary.minimumSeparationUs == 22.5 && ...
    guaranteeBoundary.collisionCount == 0, ...
    'The G-2E guarantee boundary changed.');

touching = model(60,1500,1,true);
assert(touching.minimumSeparationUs == 0 && ...
    touching.maximumOverlapUs == 0 && touching.collisionCount == 0 && ...
    ~touching.coherentTimingGuaranteeNonnegative, ...
    'Half-open intervals that only touch must not be classified as overlap.');
justOverlappingClock = model(60 + 1e-12,1500,1,true);
assert(justOverlappingClock.minimumSeparationUs < 0 && ...
    justOverlappingClock.maximumOverlapUs > 0 && ...
    justOverlappingClock.collisionCount == 1 && ...
    justOverlappingClock.unsafeOverlapDetected, ...
    'Every representable negative separation must be classified as overlap.');
translatedJustOverlappingClock = model(60 + 1e-12,1e6,1,true);
assert(isequal(translatedJustOverlappingClock.separationToNextActionUs, ...
        justOverlappingClock.separationToNextActionUs) && ...
    translatedJustOverlappingClock.collisionCount == 1 && ...
    translatedJustOverlappingClock.maximumOverlapUs > 0, ...
    'A large common epoch must not erase a representable relative overlap.');
overlappingClock = model(61,1500,1,true);
assert(overlappingClock.minimumSeparationUs == -1.5 && ...
    overlappingClock.maximumOverlapUs == 1.5 && ...
    overlappingClock.collisionCount == 1 && ...
    overlappingClock.configurationCoherent, ...
    'The coherent high-clock-error overlap limiting case changed.');
coherentButOverlapping = model(100,1500,1,true);
assert(coherentButOverlapping.newVersionSelectedForAllNodes && ...
    coherentButOverlapping.configurationCoherent && ...
    isequal(coherentButOverlapping.separationToNextActionUs, ...
        [-60 40 240 140]) && ...
    coherentButOverlapping.collisionCount == 1 && ...
    strcmp(coherentButOverlapping.scheduleState, ...
        'new-schedule-selected'), ...
    'Version coherence must not be mislabeled as sufficient timing safety.');

activationLeadsUs = [600 1000 1500];
expectedReadyNodeCount = [2 3 4];
expectedMinimumSlackUs = [-610 -210 290];
expectedWithheld = [true true false];
expectedNewVersionSelected = [false false true];
for index = 1:numel(activationLeadsUs)
    swept = model(20,activationLeadsUs(index),1,true);
    assert(swept.readyNodeCount == expectedReadyNodeCount(index) && ...
        swept.minimumActivationSlackUs == expectedMinimumSlackUs(index) && ...
        swept.newVersionSelectionWithheld == expectedWithheld(index) && ...
        swept.newVersionSelectedForAllNodes == ...
            expectedNewVersionSelected(index), ...
        'Activation-lead sweep readiness or version decision changed.');
    assert(swept.configurationCoherent && swept.collisionCount == 0 && ...
        swept.minimumSeparationUs == 60, ...
        'The version-coherent activation-lead sweep must retain one map.');
end

exactReadinessBoundary = model(20,1210,1,true);
justBelowReadinessBoundary = model(20,1210 - 1e-12,1,true);
belowReadinessBoundary = model(20,1209,1,true);
assert(exactReadinessBoundary.allNodesReady && ...
    exactReadinessBoundary.minimumActivationSlackUs == 0 && ...
    exactReadinessBoundary.newVersionSelectedForAllNodes && ...
    isequal(exactReadinessBoundary.activeScheduleVersion,[2 2 2 2]), ...
    'A node ready exactly at activation must be included.');
assert(~justBelowReadinessBoundary.allNodesReady && ...
    ~justBelowReadinessBoundary.nodeReadyAtActivation(4) && ...
    justBelowReadinessBoundary.activationSlackUs(4) < 0 && ...
    justBelowReadinessBoundary.newVersionSelectionWithheld && ...
    isequal(justBelowReadinessBoundary.activeScheduleVersion,[1 1 1 1]), ...
    'Every representable negative readiness slack must be classified as late.');
assert(~belowReadinessBoundary.allNodesReady && ...
    belowReadinessBoundary.readyNodeCount == 3 && ...
    belowReadinessBoundary.minimumActivationSlackUs == -1 && ...
    belowReadinessBoundary.newVersionSelectionWithheld && ...
    isequal(belowReadinessBoundary.activeScheduleVersion,[1 1 1 1]), ...
    'One microsecond below the readiness boundary must retain the old map.');

zeroDistributionDelay = model(20,140,0,true);
assert(isequal(zeroDistributionDelay.scheduleReadyTrueTimeUs, ...
        [80 80 120 100]) && ...
    isequal(zeroDistributionDelay.scheduleReadyLocalTimeUs, ...
        [60 90 140 90]) && ...
    zeroDistributionDelay.requiredActivationLeadUs == 140 && ...
    zeroDistributionDelay.allNodesReady && ...
    zeroDistributionDelay.minimumActivationSlackUs == 0, ...
    'Zero distribution delay must retain validation cost and exact readiness.');

coherentRetainOld = model(20,1000,1,true);
assert(isequal(coherentRetainOld.nodeReadyAtActivation, ...
        [true true true false]) && ...
    isequal(coherentRetainOld.activeScheduleVersion,[1 1 1 1]) && ...
    isequal(coherentRetainOld.selectedPhaseUs,[0 250 750 500]) && ...
    isequal(coherentRetainOld.orderedNodeIndex,[1 2 4 3]) && ...
    isequal(coherentRetainOld.separationToNextActionUs,[60 110 60 130]) && ...
    coherentRetainOld.oldVersionRetainedForAllNodes && ...
    coherentRetainOld.newVersionSelectionWithheld && ...
    coherentRetainOld.collisionCount == 0 && ...
    strcmp(coherentRetainOld.scheduleState,'old-schedule-retained'), ...
    'Coherent retain-old decision changed.');

broken = model(20,1000,1,false);
assert(isequal(broken.nodeReadyAtActivation,[true true true false]) && ...
    isequal(broken.activeScheduleVersion,[2 2 2 1]) && ...
    isequal(broken.selectedPhaseUs,[0 250 500 500]) && ...
    broken.partialNewVersionSelected && ...
    ~broken.newVersionSelectedForAllNodes && ...
    ~broken.oldVersionRetainedForAllNodes && ...
    ~broken.newVersionSelectionWithheld && ...
    ~broken.configurationCoherent, ...
    'Broken partial version selection changed.');
assert(isequal(broken.actionStartTrueTimeUs,[1020 1240 1480 1510]) && ...
    isequal(broken.orderedNodeIndex,[1 2 3 4]) && ...
    isequal(broken.separationToNextActionUs,[60 80 -130 350]) && ...
    isequal(broken.overlapDurationToNextActionUs,[0 0 130 0]) && ...
    isequal(broken.collisionFromNodeIndex,3) && ...
    isequal(broken.collisionToNodeIndex,4) && ...
    broken.collisionCount == 1 && broken.maximumOverlapUs == 130 && ...
    broken.totalOverlapUs == 130 && broken.unsafeOverlapDetected && ...
    strcmp(broken.scheduleState,'mixed-version-overlap'), ...
    'Broken Node C/Node D overlap symptom changed.');
assert(~broken.coherentTimingBoundApplicable && ...
    ~broken.coherentTimingBoundSatisfiedByActual, ...
    'The coherent guard proof must not be applied to mixed versions.');

mixedWithoutOverlap = model(20,600,1,false);
assert(isequal(mixedWithoutOverlap.nodeReadyAtActivation, ...
        [true true false false]) && ...
    isequal(mixedWithoutOverlap.activeScheduleVersion,[2 2 1 1]) && ...
    mixedWithoutOverlap.partialNewVersionSelected && ...
    ~mixedWithoutOverlap.configurationCoherent && ...
    mixedWithoutOverlap.collisionCount == 0 && ...
    ~mixedWithoutOverlap.unsafeOverlapDetected && ...
    strcmp(mixedWithoutOverlap.scheduleState, ...
        'mixed-version-no-overlap-in-fixture'), ...
    'Mixed versions without an immediate overlap must remain visible.');

recoveredActivation = model(20,1500,1,true);
assert(recoveredActivation.allNodesReady && ...
    recoveredActivation.newVersionSelectedForAllNodes && ...
    isequal(recoveredActivation.activeScheduleVersion,[2 2 2 2]) && ...
    recoveredActivation.collisionCount == 0 && ...
    recoveredActivation.minimumSeparationUs == 60, ...
    'Restored lead and policy must recover coherent version 2.');

noneReadyPolicyDisabled = model(20,0,1,false);
assert(noneReadyPolicyDisabled.readyNodeCount == 0 && ...
    ~noneReadyPolicyDisabled.partialNewVersionSelected && ...
    isequal(noneReadyPolicyDisabled.activeScheduleVersion,[1 1 1 1]) && ...
    noneReadyPolicyDisabled.oldVersionRetainedForAllNodes && ...
    ~noneReadyPolicyDisabled.newVersionSelectionWithheld && ...
    noneReadyPolicyDisabled.configurationCoherent && ...
    strcmp(noneReadyPolicyDisabled.scheduleState,'old-schedule-selected'), ...
    'No-ready-node limiting case must retain the old map without a partial switch.');

multiwayOverlap = model(250,1e6,100,true);
assert(isequal(multiwayOverlap.activeScheduleVersion,[2 2 2 2]) && ...
    isequal(multiwayOverlap.actionStartRelativeToActivationUs, ...
        [250 125 250 875]) && ...
    isequal(multiwayOverlap.orderedNodeIndex,[2 1 3 4]) && ...
    isequal(multiwayOverlap.separationToNextActionUs, ...
        [-35 -160 465 90]) && ...
    multiwayOverlap.transitionCollisionCount == 2 && ...
    multiwayOverlap.totalResourceOvercommitUs == 195, ...
    'The maximum-bound three-way occupancy fixture changed.');
assert(isequal(multiwayOverlap.collisionFromNodeIndex,[2 1 2]) && ...
    isequal(multiwayOverlap.collisionToNodeIndex,[1 3 3]) && ...
    isequal(multiwayOverlap.collisionOverlapDurationUs,[35 160 35]) && ...
    multiwayOverlap.collisionCount == 3 && ...
    multiwayOverlap.maximumOverlapUs == 160 && ...
    multiwayOverlap.totalPairwiseOverlapUs == 230 && ...
    multiwayOverlap.totalOverlapUs == 230 && ...
    multiwayOverlap.unsafeOverlapDetected, ...
    ['Three simultaneous requests must report all three conflicting pairs, ' ...
     'including the nonadjacent Node B/Node C pair.']);

bounded = multiwayOverlap;
assert(bounded.nodeCount == 4 && bounded.actionCount == 4 && ...
    bounded.scheduleVersionCount == 2 && ...
    bounded.maxCollisionPairCount == 6 && ...
    numel(bounded.clockOffsetUs) == 4 && ...
    numel(bounded.scheduleReadyLocalTimeUs) == 4 && ...
    numel(bounded.actionStartTrueTimeUs) == 4 && ...
    numel(bounded.separationToNextActionUs) == 4, ...
    'Maximum valid inputs must retain fixed four-node work.');
assert(all(isfinite(bounded.clockOffsetUs)) && ...
    all(isfinite(bounded.scheduleReadyLocalTimeUs)) && ...
    all(isfinite(bounded.actionStartTrueTimeUs)) && ...
    all(isfinite(bounded.actionEndTrueTimeUs)) && ...
    max(abs([bounded.scheduleReadyLocalTimeUs, ...
        bounded.actionStartTrueTimeUs,bounded.actionEndTrueTimeUs])) <= ...
        bounded.maxDerivedTimeUs, ...
    'Maximum valid inputs must produce finite bounded times.');
assert(bounded.maxClockErrorBoundUs == 250 && ...
    bounded.maxActivationLeadUs == 1e6 && ...
    bounded.maxDistributionDelayScale == 100 && ...
    bounded.maxDerivedTimeUs == 1.2e6 && bounded.calculationBounded, ...
    'Declared input or resource bounds changed.');

assert(baseline.sharedActivationEpochRequired && ...
    baseline.scheduleVersionCoherenceRequired && ...
    baseline.clockErrorConsumesGuardBand && ...
    baseline.truthAvailableForTeachingOnly && ...
    baseline.scheduleDistributionModeled && ...
    baseline.activationWithholdDecisionModeled && ...
    ~baseline.rollbackDecisionModeled && ...
    ~baseline.actualRollbackPerformed, ...
    'The activation-withhold or rollback claim boundary changed.');
assert(baseline.exclusiveSharedResourceRequired && ...
    baseline.nonpreemptiveResourceOccupancyModeled && ...
    strcmp(baseline.sharedResourceName,'exclusive shared channel'), ...
    'The common-resource collision premise changed.');
assert(~baseline.readinessAcknowledgmentModeled && ...
    ~baseline.transactionalCommitProtocolModeled && ...
    ~baseline.configurationMessageEncodingModeled && ...
    ~baseline.configurationIntegrityModeled && ...
    ~baseline.clockRateErrorModeled && ~baseline.clockServoModeled && ...
    ~baseline.packetLossModeled && ~baseline.networkIoPerformed && ...
    ~baseline.physicalHardwareUsed && ~baseline.fullTsnProtocolModeled && ...
    ~baseline.fullTteProtocolModeled, ...
    'The protocol, clock, network, or hardware abstraction boundary changed.');
assert(~baseline.timeoutModeled && ~baseline.cancellationModeled && ...
    ~baseline.backgroundCancellationModeled && ...
    ~baseline.actualWaitPerformed, ...
    'The finite analytical model must not imply timeout, cancellation, or waits.');

assertThrows(@() model([],1500,1,true), ...
    'P08:InvalidClockErrorBound');
assertThrows(@() model('20',1500,1,true), ...
    'P08:InvalidClockErrorBound');
assertThrows(@() model([20 21],1500,1,true), ...
    'P08:InvalidClockErrorBound');
assertThrows(@() model(20 + 1i,1500,1,true), ...
    'P08:InvalidClockErrorBound');
assertThrows(@() model(NaN,1500,1,true), ...
    'P08:InvalidClockErrorBound');
assertThrows(@() model(Inf,1500,1,true), ...
    'P08:InvalidClockErrorBound');
assertThrows(@() model(-1,1500,1,true), ...
    'P08:InvalidClockErrorBound');
assertThrows(@() model(251,1500,1,true), ...
    'P08:InvalidClockErrorBound');

assertThrows(@() model(20,[],1,true), ...
    'P08:InvalidActivationLead');
assertThrows(@() model(20,'1500',1,true), ...
    'P08:InvalidActivationLead');
assertThrows(@() model(20,[1500 1501],1,true), ...
    'P08:InvalidActivationLead');
assertThrows(@() model(20,1500 + 1i,1,true), ...
    'P08:InvalidActivationLead');
assertThrows(@() model(20,NaN,1,true), ...
    'P08:InvalidActivationLead');
assertThrows(@() model(20,Inf,1,true), ...
    'P08:InvalidActivationLead');
assertThrows(@() model(20,-1,1,true), ...
    'P08:InvalidActivationLead');
assertThrows(@() model(20,1e6 + 1,1,true), ...
    'P08:InvalidActivationLead');

assertThrows(@() model(20,1500,[],true), ...
    'P08:InvalidDistributionScale');
assertThrows(@() model(20,1500,'1',true), ...
    'P08:InvalidDistributionScale');
assertThrows(@() model(20,1500,[1 2],true), ...
    'P08:InvalidDistributionScale');
assertThrows(@() model(20,1500,1 + 1i,true), ...
    'P08:InvalidDistributionScale');
assertThrows(@() model(20,1500,NaN,true), ...
    'P08:InvalidDistributionScale');
assertThrows(@() model(20,1500,Inf,true), ...
    'P08:InvalidDistributionScale');
assertThrows(@() model(20,1500,-0.1,true), ...
    'P08:InvalidDistributionScale');
assertThrows(@() model(20,1500,101,true), ...
    'P08:InvalidDistributionScale');

assertThrows(@() model(20,1500,1,[]), ...
    'P08:InvalidActivationPolicy');
assertThrows(@() model(20,1500,1,'true'), ...
    'P08:InvalidActivationPolicy');
assertThrows(@() model(20,1500,1,[true false]), ...
    'P08:InvalidActivationPolicy');
assertThrows(@() model(20,1500,1,1 + 1i), ...
    'P08:InvalidActivationPolicy');
assertThrows(@() model(20,1500,1,NaN), ...
    'P08:InvalidActivationPolicy');
assertThrows(@() model(20,1500,1,Inf), ...
    'P08:InvalidActivationPolicy');
assertThrows(@() model(20,1500,1,-1), ...
    'P08:InvalidActivationPolicy');
assertThrows(@() model(20,1500,1,0.5), ...
    'P08:InvalidActivationPolicy');
assertThrows(@() model(20,1500,1,2), ...
    'P08:InvalidActivationPolicy');

recovered = model(20,1500,1,true);
assert(isequal(recovered.clockOffsetUs,baseline.clockOffsetUs) && ...
    isequal(recovered.scheduleReadyLocalTimeUs, ...
        baseline.scheduleReadyLocalTimeUs) && ...
    isequal(recovered.activeScheduleVersion, ...
        baseline.activeScheduleVersion) && ...
    isequal(recovered.actionStartTrueTimeUs, ...
        baseline.actionStartTrueTimeUs) && ...
    isequal(recovered.separationToNextActionUs, ...
        baseline.separationToNextActionUs), ...
    'A valid call after malformed inputs must recover with no retained state.');

disp(['P08 checks passed: shared-clock timing, coherent readiness, two sweeps, ' ...
    'mixed-version branches, exhaustive collision pairs, retain-old decision, ' ...
    'limits, malformed inputs, and recovery.']);
end

function assertThrows(action,expectedIdentifier)
didThrow = false;
try
    action();
catch exception
    didThrow = true;
    assert(strcmp(exception.identifier,expectedIdentifier), ...
        'Expected %s but received %s.',expectedIdentifier,exception.identifier);
end
assert(didThrow,'Expected error %s was not thrown.',expectedIdentifier);
end
