function run_checks
%RUN_CHECKS Independent deterministic checks for the P05 timestamp model.

baseline = model(8,7,3,8,0,3);
defaulted = model();
expectedSampleIndex = (1:8)';
expectedSendTimeMs = (0:20:140)';
expectedQueueShape = [0 0.25 0.75 0.5 1 0.25 0.5 0]';
expectedQueueDelayMs = [0 2 6 4 8 2 4 0]';
expectedNetworkDelayMs = [3 5 9 7 11 5 7 3]';
expectedArrivalTimeMs = [3 25 49 67 91 105 127 143]';
expectedReceiverTimestampMs = [10 32 56 74 98 112 134 150]';
expectedObservationMs = [10 12 16 14 18 12 14 10]';

assert(isequal(defaulted.observedTimestampDifferenceMs, ...
        baseline.observedTimestampDifferenceMs) && ...
    defaulted.estimatedClockOffsetMs == baseline.estimatedClockOffsetMs && ...
    isequal(defaulted.estimatedNetworkDelayMs, ...
        baseline.estimatedNetworkDelayMs), ...
    'No-argument defaults must reproduce the displayed baseline.');
assert(isequal(baseline.sampleIndex,expectedSampleIndex) && ...
    isequal(baseline.trueSendTimeMs,expectedSendTimeMs) && ...
    isequal(baseline.senderTimestampMs,expectedSendTimeMs), ...
    'Baseline sample and sender timestamps changed.');
assert(isequal(baseline.queueShape,expectedQueueShape) && ...
    isequal(baseline.variableQueueDelayMs,expectedQueueDelayMs), ...
    'Baseline deterministic queue profile changed.');
assert(isequal(baseline.trueNetworkDelayMs,expectedNetworkDelayMs) && ...
    isequal(baseline.trueArrivalTimeMs,expectedArrivalTimeMs), ...
    'Baseline true network delay or arrival time changed.');
assert(isequal(baseline.receiverTimestampMs,expectedReceiverTimestampMs) && ...
    isequal(baseline.observedTimestampDifferenceMs,expectedObservationMs), ...
    'Baseline receiver timestamp or cross-clock observation changed.');
assert(isequal(baseline.observedTimestampDifferenceMs, ...
    baseline.receiverTimestampMs - baseline.senderTimestampMs), ...
    'Each observable must be receiver timestamp minus sender timestamp.');
assert(isequal(baseline.observedTimestampDifferenceMs, ...
    baseline.clockOffsetMs + baseline.trueNetworkDelayMs), ...
    'Each one-way observation must equal offset plus true network delay.');
assert(baseline.minimumObservedDifferenceMs == 10 && ...
    baseline.estimatedClockOffsetMs == 7 && baseline.clockOffsetErrorMs == 0, ...
    'The exact attainable floor must recover the baseline offset.');
assert(isequal(baseline.estimatedNetworkDelayMs,expectedNetworkDelayMs) && ...
    isequal(baseline.estimatedVariableDelayMs,expectedQueueDelayMs), ...
    'The anchored baseline delay decomposition changed.');
assert(all(baseline.networkDelayErrorMs == 0) && ...
    all(baseline.reconstructionResidualMs == 0) && ...
    baseline.maxAbsReconstructionResidualMs == 0, ...
    'The baseline decomposition must reconstruct the observation exactly.');
assert(baseline.trueMinimumNetworkDelayMs == 3 && ...
    baseline.trueMaximumNetworkDelayMs == 11 && ...
    baseline.trueNetworkDelaySpreadMs == 8 && ...
    baseline.observedDifferenceSpreadMs == 8, ...
    'Baseline delay bounds and offset-invariant spread changed.');
assert(baseline.meanTrueNetworkDelayMs == 6.25 && ...
    baseline.meanEstimatedNetworkDelayMs == 6.25 && ...
    mean(baseline.variableQueueDelayMs) == 3.25 && ...
    mean(baseline.observedTimestampDifferenceMs) == 13.25, ...
    'Baseline mean metrics changed.');
assert(baseline.minimumDelayAnchorSatisfiedInTruth && ...
    strcmp(baseline.identifiabilityState,'anchored-separation') && ...
    baseline.zeroVariableQueueSamplePresent, ...
    'The simulation truth must mark the baseline anchor as satisfied.');
assert(baseline.minimumDelayAnchorAssumed && ...
    ~baseline.decompositionUniqueFromOneWayOnly && ...
    baseline.constantDelayAliasesWithClockOffset, ...
    'The external-anchor and one-way-identifiability boundary must remain explicit.');
assert(baseline.timestampPairingAssumed && baseline.truthAvailableForTeachingOnly && ...
    ~baseline.measurementNoiseModeled && ~baseline.clockSkewModeled && ...
    ~baseline.twoWayExchangeModeled, ...
    'Pairing, truth, noise, skew, and two-way-exchange assumptions changed.');
assert(~baseline.timeoutModeled && ~baseline.cancellationModeled && ...
    ~baseline.actualWaitPerformed, ...
    'The finite model must not imply timeout, cancellation, or wall-clock waits.');

repeated = model(8,7,3,8,0,3);
assert(isequal(repeated.receiverTimestampMs,baseline.receiverTimestampMs) && ...
    isequal(repeated.observedTimestampDifferenceMs, ...
        baseline.observedTimestampDifferenceMs) && ...
    isequal(repeated.estimatedNetworkDelayMs, ...
        baseline.estimatedNetworkDelayMs), ...
    'Identical inputs must reproduce the complete deterministic trace.');
typed = model(uint8(8),int8(7),uint8(3),uint8(8),uint8(0),uint8(3));
assert(isequal(typed.observedTimestampDifferenceMs, ...
        baseline.observedTimestampDifferenceMs) && ...
    typed.estimatedClockOffsetMs == baseline.estimatedClockOffsetMs, ...
    'Accepted integer-class inputs must normalize to baseline arithmetic.');
fractional = model(8,-0.5,1.25,2.5,0.75,2);
assert(fractional.minimumDelayAnchorSatisfiedInTruth && ...
    fractional.estimatedClockOffsetMs == -0.5 && ...
    max(abs(fractional.networkDelayErrorMs)) == 0, ...
    'Finite fractional time inputs must preserve anchored arithmetic.');

clockOffsetsMs = [-8 0 12];
expectedObservedMinimumMs = [-5 3 15];
for index = 1:numel(clockOffsetsMs)
    swept = model(8,clockOffsetsMs(index),3,8,0,3);
    assert(swept.estimatedClockOffsetMs == clockOffsetsMs(index) && ...
        swept.minimumObservedDifferenceMs == expectedObservedMinimumMs(index), ...
        'Clock-offset sweep estimate or lower envelope changed.');
    assert(swept.observedDifferenceSpreadMs == 8 && ...
        isequal(swept.estimatedNetworkDelayMs,expectedNetworkDelayMs), ...
        'Clock offset must translate observations without changing delay shape.');
end

queuePeaksMs = [0 4 12];
expectedQueueSpreadMs = [0 4 12];
expectedMaximumDelayMs = [3 7 15];
for index = 1:numel(queuePeaksMs)
    swept = model(8,7,3,queuePeaksMs(index),0,3);
    assert(swept.estimatedClockOffsetMs == 7 && ...
        swept.observedDifferenceSpreadMs == expectedQueueSpreadMs(index) && ...
        swept.trueMaximumNetworkDelayMs == expectedMaximumDelayMs(index), ...
        'Queue-delay sweep must change spread without moving the valid offset anchor.');
end

zeroOffset = model(8,0,3,8,0,3);
assert(isequal(zeroOffset.observedTimestampDifferenceMs, ...
        zeroOffset.trueNetworkDelayMs) && ...
    zeroOffset.estimatedClockOffsetMs == 0, ...
    'At zero offset, cross-clock differences must equal true network delay.');
negativeOffset = model(8,-20,3,8,0,3);
assert(any(negativeOffset.observedTimestampDifferenceMs < 0) && ...
    all(negativeOffset.trueNetworkDelayMs >= 0) && ...
    negativeOffset.estimatedClockOffsetMs == -20, ...
    'A negative timestamp difference must coexist with nonnegative physical delay.');
zeroQueue = model(8,7,3,0,0,3);
assert(all(zeroQueue.trueNetworkDelayMs == 3) && ...
    all(zeroQueue.observedTimestampDifferenceMs == 10) && ...
    zeroQueue.observedDifferenceSpreadMs == 0 && ...
    zeroQueue.estimatedClockOffsetMs == 7, ...
    'Zero variable queueing must produce a flat anchored trace.');
oneSample = model(1,7,3,8,0,3);
assert(oneSample.sampleCount == 1 && oneSample.variableQueueDelayMs == 0 && ...
    oneSample.observedTimestampDifferenceMs == 10 && ...
    oneSample.estimatedClockOffsetMs == 7, ...
    'The one-sample fixture separates only because it reaches the supplied floor.');

broken = model(8,7,3,8,5,3);
aliased = model(8,12,3,8,0,3);
expectedBrokenTrueDelayMs = [8 10 14 12 16 10 12 8]';
expectedBrokenObservationMs = [15 17 21 19 23 17 19 15]';
assert(isequal(broken.trueNetworkDelayMs,expectedBrokenTrueDelayMs) && ...
    isequal(broken.observedTimestampDifferenceMs,expectedBrokenObservationMs), ...
    'The hidden-common-delay broken trace changed.');
assert(isequal(broken.observedTimestampDifferenceMs, ...
        aliased.observedTimestampDifferenceMs) && ...
    broken.clockOffsetMs ~= aliased.clockOffsetMs && ...
    ~isequal(broken.trueNetworkDelayMs,aliased.trueNetworkDelayMs), ...
    'Distinct clock/delay truths must remain exactly aliased in one-way observations.');
assert(broken.estimatedClockOffsetMs == 12 && broken.clockOffsetErrorMs == 5 && ...
    isequal(broken.estimatedNetworkDelayMs,expectedNetworkDelayMs) && ...
    all(broken.networkDelayErrorMs == -5), ...
    'The false floor must assign hidden constant delay to clock offset.');
assert(broken.maxAbsReconstructionResidualMs == 0 && ...
    ~broken.minimumDelayAnchorSatisfiedInTruth && ...
    strcmp(broken.identifiabilityState,'ambiguous-common-delay'), ...
    'Perfect reconstruction must not conceal the false-anchor truth diagnostic.');
assert(aliased.minimumDelayAnchorSatisfiedInTruth && ...
    aliased.clockOffsetErrorMs == 0 && ...
    aliased.maxAbsReconstructionResidualMs == 0, ...
    'The observational alias must be a distinct valid anchored decomposition.');

miscalibrated = model(8,7,3,8,0,4);
assert(miscalibrated.estimatedClockOffsetMs == 6 && ...
    miscalibrated.clockOffsetErrorMs == -1 && ...
    all(miscalibrated.networkDelayErrorMs == 1) && ...
    ~miscalibrated.minimumDelayAnchorSatisfiedInTruth, ...
    'An assumed lower floor must bias offset and delay equally and oppositely.');
hiddenButAnchored = model(8,7,3,8,5,8);
assert(hiddenButAnchored.minimumDelayAnchorSatisfiedInTruth && ...
    hiddenButAnchored.estimatedClockOffsetMs == 7 && ...
    isequal(hiddenButAnchored.estimatedNetworkDelayMs, ...
        hiddenButAnchored.trueNetworkDelayMs), ...
    'The anchor must represent the attainable total fixed-delay floor.');

bounded = model(64,-1e6,1e6,1e6,0,1e6);
assert(numel(bounded.sampleIndex) == 64 && ...
    all(isfinite(bounded.observedTimestampDifferenceMs)) && ...
    all(isfinite(bounded.estimatedNetworkDelayMs)) && ...
    bounded.estimatedClockOffsetMs == -1e6, ...
    'The maximum-magnitude valid case must remain finite and anchored.');
assert(bounded.queueProfileAccessCount == 64 && ...
    bounded.maxQueueProfileAccessCount == 64 && ...
    bounded.maxSampleCount == 64 && bounded.maxTimeMagnitudeMs == 1e6 && ...
    bounded.maxAbsReconstructionResidualMs <= bounded.comparisonToleranceMs, ...
    'The fixed sample and numerical resource bounds changed.');
brokenMany = model(64,7,3,8,5,3);
aliasMany = model(64,12,3,8,0,3);
assert(isequal(brokenMany.observedTimestampDifferenceMs, ...
        aliasMany.observedTimestampDifferenceMs) && ...
    brokenMany.clockOffsetErrorMs == 5, ...
    'More samples with the same hidden floor must not remove one-way aliasing.');

assertThrows(@() model(0,7,3,8,0,3),'P05:InvalidSampleCount');
assertThrows(@() model(65,7,3,8,0,3),'P05:InvalidSampleCount');
assertThrows(@() model(1.5,7,3,8,0,3),'P05:InvalidSampleCount');
assertThrows(@() model(NaN,7,3,8,0,3),'P05:InvalidSampleCount');
assertThrows(@() model([8 9],7,3,8,0,3),'P05:InvalidSampleCount');
assertThrows(@() model(1 + 1i,7,3,8,0,3),'P05:InvalidSampleCount');
assertThrows(@() model(8,Inf,3,8,0,3),'P05:InvalidClockOffset');
assertThrows(@() model(8,NaN,3,8,0,3),'P05:InvalidClockOffset');
assertThrows(@() model(8,1e6 + 1,3,8,0,3),'P05:InvalidClockOffset');
assertThrows(@() model(8,-1e6 - 1,3,8,0,3),'P05:InvalidClockOffset');
assertThrows(@() model(8,[7 8],3,8,0,3),'P05:InvalidClockOffset');
assertThrows(@() model(8,7 + 1i,3,8,0,3),'P05:InvalidClockOffset');
assertThrows(@() model(8,7,-1,8,0,3),'P05:InvalidPropagationDelay');
assertThrows(@() model(8,7,Inf,8,0,3),'P05:InvalidPropagationDelay');
assertThrows(@() model(8,7,NaN,8,0,3),'P05:InvalidPropagationDelay');
assertThrows(@() model(8,7,1e6 + 1,8,0,3),'P05:InvalidPropagationDelay');
assertThrows(@() model(8,7,[3 4],8,0,3),'P05:InvalidPropagationDelay');
assertThrows(@() model(8,7,3 + 1i,8,0,3),'P05:InvalidPropagationDelay');
assertThrows(@() model(8,7,3,-1,0,3),'P05:InvalidQueuePeakDelay');
assertThrows(@() model(8,7,3,Inf,0,3),'P05:InvalidQueuePeakDelay');
assertThrows(@() model(8,7,3,NaN,0,3),'P05:InvalidQueuePeakDelay');
assertThrows(@() model(8,7,3,1e6 + 1,0,3),'P05:InvalidQueuePeakDelay');
assertThrows(@() model(8,7,3,[8 9],0,3),'P05:InvalidQueuePeakDelay');
assertThrows(@() model(8,7,3,8 + 1i,0,3),'P05:InvalidQueuePeakDelay');
assertThrows(@() model(8,7,3,8,-1,3),'P05:InvalidHiddenCommonDelay');
assertThrows(@() model(8,7,3,8,Inf,3),'P05:InvalidHiddenCommonDelay');
assertThrows(@() model(8,7,3,8,NaN,3),'P05:InvalidHiddenCommonDelay');
assertThrows(@() model(8,7,3,8,1e6 + 1,3),'P05:InvalidHiddenCommonDelay');
assertThrows(@() model(8,7,3,8,[0 5],3),'P05:InvalidHiddenCommonDelay');
assertThrows(@() model(8,7,3,8,1i,3),'P05:InvalidHiddenCommonDelay');
assertThrows(@() model(8,7,3,8,0,-1),'P05:InvalidAssumedMinimumDelay');
assertThrows(@() model(8,7,3,8,0,Inf),'P05:InvalidAssumedMinimumDelay');
assertThrows(@() model(8,7,3,8,0,NaN),'P05:InvalidAssumedMinimumDelay');
assertThrows(@() model(8,7,3,8,0,1e6 + 1),'P05:InvalidAssumedMinimumDelay');
assertThrows(@() model(8,7,3,8,0,[3 4]),'P05:InvalidAssumedMinimumDelay');
assertThrows(@() model(8,7,3,8,0,3 + 1i),'P05:InvalidAssumedMinimumDelay');

recovered = model(8,7,3,8,0,3);
assert(isequal(recovered.observedTimestampDifferenceMs, ...
        baseline.observedTimestampDifferenceMs) && ...
    isequal(recovered.estimatedNetworkDelayMs, ...
        baseline.estimatedNetworkDelayMs) && ...
    recovered.estimatedClockOffsetMs == baseline.estimatedClockOffsetMs, ...
    'A valid call after malformed inputs must recover with no retained state.');

disp(['P05 checks passed: timestamp sums, anchored separation, two sweeps, ' ...
    'one-way aliasing, malformed inputs, bounds, and recovery.']);
end

function assertThrows(action,expectedIdentifier)
didThrow = false;
try
    action();
catch exception
    didThrow = true;
    assert(strcmp(exception.identifier,expectedIdentifier), ...
        'Expected %s but received %s.',expectedIdentifier,exception.identifier);
end
assert(didThrow,'Expected error %s was not thrown.',expectedIdentifier);
end
