function run_checks
%RUN_CHECKS Independent deterministic checks for the P04 FIFO queue model.

baseline = model(12,4,6,4,20,1);
defaulted = model();
expectedArrival = (0:4:44)';
expectedAccepted = logical([1 1 1 1 1 1 1 1 1 1 0 1]');
expectedServiceStart = [0 6 12 18 24 30 36 42 48 54 NaN 60]';
expectedDeparture = [6 12 18 24 30 36 42 48 54 60 NaN 66]';
expectedWaiting = [0 2 4 6 8 10 12 14 16 18 NaN 16]';
expectedLatency = [6 8 10 12 14 16 18 20 22 24 NaN 22]';
expectedUnfinishedBefore = [0 1 1 1 2 2 2 3 3 3 4 3]';
expectedOccupancyAfter = [1 2 2 2 3 3 3 4 4 4 4 4]';

assert(isequaln(defaulted.systemLatencyMs,baseline.systemLatencyMs) && ...
    isequal(defaulted.droppedMask,baseline.droppedMask) && ...
    defaulted.deadlineMs == baseline.deadlineMs, ...
    'No-argument defaults must reproduce the displayed baseline.');
assert(isequal(baseline.arrivalTimeMs,expectedArrival), ...
    'Baseline periodic arrivals changed.');
assert(isequal(baseline.acceptedMask,expectedAccepted) && ...
    isequal(baseline.droppedMask,~expectedAccepted), ...
    'Baseline admission and tail-drop decisions changed.');
assert(isequaln(baseline.serviceStartTimeMs,expectedServiceStart), ...
    'Baseline FIFO service starts changed.');
assert(isequaln(baseline.departureTimeMs,expectedDeparture), ...
    'Baseline departures changed.');
assert(isequaln(baseline.waitingTimeMs,expectedWaiting), ...
    'Baseline waiting times changed.');
assert(isequaln(baseline.systemLatencyMs,expectedLatency), ...
    'Baseline system latencies changed.');
assert(isequal(baseline.unfinishedBeforeArrivalCount,expectedUnfinishedBefore) && ...
    isequal(baseline.systemOccupancyAfterArrivalCount,expectedOccupancyAfter), ...
    'Baseline finite-capacity occupancy changed.');
assert(baseline.messageCount == baseline.acceptedCount + baseline.droppedCount && ...
    baseline.acceptedCount == 11 && baseline.droppedCount == 1, ...
    'Offered work must equal accepted plus dropped work.');
assert(baseline.onTimeCount == 8 && baseline.lateCount == 3 && ...
    baseline.onTimeCount + baseline.lateCount == baseline.acceptedCount, ...
    'Baseline deadline classification changed.');
assert(baseline.maxWaitingTimeMs == 18 && ...
    baseline.maxSystemLatencyMs == 24 && ...
    abs(baseline.meanWaitingTimeMs - 106/11) < 1e-12 && ...
    abs(baseline.meanSystemLatencyMs - 172/11) < 1e-12, ...
    'Baseline waiting and latency metrics changed.');
assert(baseline.observationHorizonMs == 66 && baseline.busyTimeMs == 66 && ...
    baseline.systemTimeAreaMessageMs == 172 && ...
    abs(baseline.meanSystemOccupancyByArea - 172/66) < 1e-12, ...
    'Baseline finite-horizon area metrics changed.');
assert(baseline.nominalUtilization == 1.5 && ...
    strcmp(baseline.nominalLoadState,'overloaded') && ...
    strcmp(baseline.queueState,'capacity-limited-with-drops'), ...
    'Baseline load state changed.');
assert(baseline.peakSystemOccupancyCount <= baseline.capacityMessages && ...
    baseline.peakSystemOccupancyCount == 4 && baseline.peakWaitingCount == 3, ...
    'Baseline occupancy must stay within the explicit total-system capacity.');
assert(all(isnan(baseline.serviceStartTimeMs(baseline.droppedMask))) && ...
    all(isnan(baseline.departureTimeMs(baseline.droppedMask))) && ...
    all(isnan(baseline.waitingTimeMs(baseline.droppedMask))) && ...
    all(isnan(baseline.systemLatencyMs(baseline.droppedMask))), ...
    'Dropped records must have undefined service and latency values.');
assert(baseline.departureTimeMs(12) == 66, ...
    'The dropped record must not advance the server before record 12.');

accepted = baseline.acceptedMask;
assert(all(baseline.serviceStartTimeMs(accepted) >= ...
    baseline.arrivalTimeMs(accepted)), ...
    'Accepted service cannot begin before arrival.');
assert(max(abs(baseline.departureTimeMs(accepted) - ...
    baseline.serviceStartTimeMs(accepted) - baseline.serviceTimeMs)) < 1e-12, ...
    'Each accepted departure must be one service time after its start.');
assert(max(abs(baseline.systemLatencyMs(accepted) - ...
    baseline.waitingTimeMs(accepted) - baseline.serviceTimeMs)) < 1e-12, ...
    'System latency must decompose into FIFO waiting plus service.');
assert(all(diff(baseline.departureTimeMs(accepted)) > 0), ...
    'Accepted departures must retain FIFO record order.');
assert(baseline.capacityIncludesService && ...
    baseline.departureBeforeCoincidentArrival && baseline.fifoTiesUseRecordIndex && ...
    strcmp(baseline.dropPolicy,'tail-drop-on-arrival'), ...
    'Admission, tie, and drop policies must remain explicit.');
assert(baseline.deadlineOnlyClassifies && ~baseline.cancellationModeled && ...
    ~baseline.timeoutModeled && ~baseline.actualWaitPerformed, ...
    'The finite model must not imply cancellation, timeout, or wall-clock waits.');

repeated = model(12,4,6,4,20,1);
assert(isequaln(repeated.systemLatencyMs,baseline.systemLatencyMs) && ...
    isequal(repeated.systemOccupancyAfterArrivalCount, ...
        baseline.systemOccupancyAfterArrivalCount), ...
    'Identical inputs must reproduce the complete deterministic queue.');
typed = model(uint8(12),uint8(4),uint8(6),uint8(4),uint8(20),uint8(1));
assert(isequaln(typed.systemLatencyMs,baseline.systemLatencyMs) && ...
    isequal(typed.acceptedMask,baseline.acceptedMask), ...
    'Accepted integer-class inputs must normalize to baseline arithmetic.');

oneRecord = model(1,100,6,1,6,1);
assert(oneRecord.acceptedCount == 1 && oneRecord.droppedCount == 0 && ...
    oneRecord.waitingTimeMs == 0 && oneRecord.systemLatencyMs == 6 && ...
    oneRecord.onTimeCount == 1 && oneRecord.observationHorizonMs == 6, ...
    'The one-record limit must be one immediate service interval.');
underloaded = model(8,8,6,1,6,1);
assert(underloaded.nominalUtilization == 0.75 && ...
    all(underloaded.waitingTimeMs == 0) && underloaded.droppedCount == 0 && ...
    underloaded.onTimeCount == 8 && strcmp(underloaded.queueState,'no-backlog'), ...
    'Periodic underload must drain before each next arrival.');
critical = model(8,6,6,1,6,1);
assert(critical.nominalUtilization == 1 && ...
    all(critical.waitingTimeMs == 0) && critical.droppedCount == 0 && ...
    critical.onTimeCount == 8 && strcmp(critical.nominalLoadState,'critical'), ...
    'A departure exactly at each arrival must free capacity first.');

deadlineEqual = model(3,4,6,8,10,1);
deadlineBelow = model(3,4,6,8,9.999,1);
assert(isequal(deadlineEqual.systemLatencyMs,[6 8 10]') && ...
    deadlineEqual.onTimeCount == 3 && deadlineBelow.onTimeCount == 2, ...
    'Delivery exactly at the deadline must count as on time.');
assert(isequal(deadlineEqual.departureTimeMs,deadlineBelow.departureTimeMs) && ...
    isequal(deadlineEqual.systemLatencyMs,deadlineBelow.systemLatencyMs), ...
    'A deadline must classify, never alter, queue service.');

arrivalPeriods = [4 6 8];
expectedArrivalUtilization = [1.5 1 0.75];
expectedArrivalOnTime = [8 12 12];
expectedArrivalDropped = [1 0 0];
expectedArrivalMaxLatency = [24 6 6];
actualArrivalUtilization = zeros(size(arrivalPeriods));
actualArrivalOnTime = zeros(size(arrivalPeriods));
actualArrivalDropped = zeros(size(arrivalPeriods));
actualArrivalMaxLatency = zeros(size(arrivalPeriods));
for index = 1:numel(arrivalPeriods)
    swept = model(12,arrivalPeriods(index),6,4,20,1);
    actualArrivalUtilization(index) = swept.nominalUtilization;
    actualArrivalOnTime(index) = swept.onTimeCount;
    actualArrivalDropped(index) = swept.droppedCount;
    actualArrivalMaxLatency(index) = swept.maxSystemLatencyMs;
end
assert(max(abs(actualArrivalUtilization - expectedArrivalUtilization)) < 1e-12 && ...
    isequal(actualArrivalOnTime,expectedArrivalOnTime) && ...
    isequal(actualArrivalDropped,expectedArrivalDropped) && ...
    isequal(actualArrivalMaxLatency,expectedArrivalMaxLatency), ...
    'Arrival-period sweep changed.');

capacityValues = [1 2 4 8];
expectedCapacityOnTime = [6 9 8 8];
expectedCapacityLate = [0 0 3 4];
expectedCapacityDropped = [6 3 1 0];
expectedCapacityMaxLatency = [6 12 24 28];
actualCapacityOnTime = zeros(size(capacityValues));
actualCapacityLate = zeros(size(capacityValues));
actualCapacityDropped = zeros(size(capacityValues));
actualCapacityMaxLatency = zeros(size(capacityValues));
for index = 1:numel(capacityValues)
    swept = model(12,4,6,capacityValues(index),20,1);
    actualCapacityOnTime(index) = swept.onTimeCount;
    actualCapacityLate(index) = swept.lateCount;
    actualCapacityDropped(index) = swept.droppedCount;
    actualCapacityMaxLatency(index) = swept.maxSystemLatencyMs;
end
assert(isequal(actualCapacityOnTime,expectedCapacityOnTime) && ...
    isequal(actualCapacityLate,expectedCapacityLate) && ...
    isequal(actualCapacityDropped,expectedCapacityDropped) && ...
    isequal(actualCapacityMaxLatency,expectedCapacityMaxLatency), ...
    'Capacity sweep changed.');

smooth = model(8,10,6,8,15,1);
broken = model(8,10,6,8,15,4);
expectedBurstArrival = [0 10 20 60 60 60 60 70]';
expectedBurstWaiting = [0 0 0 0 6 12 18 14]';
expectedBurstLatency = [6 6 6 6 12 18 24 20]';
assert(isequal(broken.arrivalTimeMs,expectedBurstArrival) && ...
    isequal(broken.waitingTimeMs,expectedBurstWaiting) && ...
    isequal(broken.systemLatencyMs,expectedBurstLatency), ...
    'The deterministic P03 release-burst recurrence changed.');
assert(smooth.nominalUtilization == broken.nominalUtilization && ...
    broken.nominalUtilization == 0.6 && smooth.droppedCount == 0 && ...
    broken.droppedCount == 0,'The broken case must isolate arrival shape below average capacity.');
assert(smooth.maxSystemLatencyMs == 6 && smooth.lateCount == 0 && ...
    broken.maxSystemLatencyMs == 24 && broken.lateCount == 3 && ...
    strcmp(broken.queueState,'transient-burst-backlog'), ...
    'The broken average-rate assumption must have a visible deadline symptom.');

burstOverflow = model(8,10,6,2,15,4);
expectedOverflowAccepted = logical([1 1 1 1 1 0 0 1]');
expectedOverflowServiceStart = [0 10 20 60 66 NaN NaN 72]';
expectedOverflowDeparture = [6 16 26 66 72 NaN NaN 78]';
expectedOverflowWaiting = [0 0 0 0 6 NaN NaN 2]';
expectedOverflowLatency = [6 6 6 6 12 NaN NaN 8]';
expectedOverflowUnfinishedBefore = [0 0 0 0 1 2 2 1]';
assert(isequal(burstOverflow.acceptedMask,expectedOverflowAccepted) && ...
    isequal(burstOverflow.droppedMask,~expectedOverflowAccepted), ...
    'An equal-time burst must admit in record order and tail-drop once capacity is full.');
assert(isequaln(burstOverflow.serviceStartTimeMs,expectedOverflowServiceStart) && ...
    isequaln(burstOverflow.departureTimeMs,expectedOverflowDeparture) && ...
    isequaln(burstOverflow.waitingTimeMs,expectedOverflowWaiting) && ...
    isequaln(burstOverflow.systemLatencyMs,expectedOverflowLatency), ...
    'Burst overflow must preserve FIFO service and leave dropped times undefined.');
assert(isequal(burstOverflow.unfinishedBeforeArrivalCount, ...
        expectedOverflowUnfinishedBefore) && ...
    burstOverflow.peakSystemOccupancyCount == 2 && ...
    burstOverflow.droppedCount == 2 && burstOverflow.onTimeCount == 6 && ...
    burstOverflow.departureTimeMs(8) == 78, ...
    'The queue must recover capacity after the burst and admit the later record.');

largeTimestampBoundary = model(64,1e6,1e6,1,1e6,1);
assert(all(largeTimestampBoundary.waitingTimeMs == 0) && ...
    largeTimestampBoundary.acceptedCount == 64 && ...
    largeTimestampBoundary.onTimeCount == 64 && ...
    largeTimestampBoundary.droppedCount == 0, ...
    'Large exact-time arrivals must not create numerical waiting or drops.');
bounded = model(64,1,64,64,1000,8);
assert(numel(bounded.recordIndex) == 64 && bounded.acceptedCount == 64 && ...
    bounded.peakSystemOccupancyCount == 64 && ...
    bounded.peakSystemOccupancyCount <= bounded.capacityMessages, ...
    'The resource-bound case must keep fixed output and occupancy bounds.');
assert(bounded.admissionComparisonCount == 2016 && ...
    bounded.maxAdmissionComparisonCount == 2016 && ...
    bounded.maxMessageCount == 64 && bounded.maxCapacityMessages == 64 && ...
    bounded.maxReleaseBatchMessages == 8, ...
    'The finite model resource bounds changed.');
typedBounded = model(uint8(64),uint8(1),uint8(64),uint8(64),uint16(1000),uint8(8));
assert(isequal(typedBounded.arrivalTimeMs,bounded.arrivalTimeMs) && ...
    isequal(typedBounded.systemOccupancyAfterArrivalCount, ...
        bounded.systemOccupancyAfterArrivalCount), ...
    'Typed inputs at resource bounds must normalize without saturation.');

assertThrows(@() model(0,4,6,4,20,1),'P04:InvalidMessageCount');
assertThrows(@() model(65,4,6,4,20,1),'P04:InvalidMessageCount');
assertThrows(@() model(1.5,4,6,4,20,1),'P04:InvalidMessageCount');
assertThrows(@() model(NaN,4,6,4,20,1),'P04:InvalidMessageCount');
assertThrows(@() model([12 13],4,6,4,20,1),'P04:InvalidMessageCount');
assertThrows(@() model(1 + 1i,4,6,4,20,1),'P04:InvalidMessageCount');
assertThrows(@() model(12,0,6,4,20,1),'P04:InvalidArrivalPeriod');
assertThrows(@() model(12,Inf,6,4,20,1),'P04:InvalidArrivalPeriod');
assertThrows(@() model(12,[4 6],6,4,20,1),'P04:InvalidArrivalPeriod');
assertThrows(@() model(12,1e6 + 1,6,4,20,1),'P04:InvalidArrivalPeriod');
assertThrows(@() model(12,4,0,4,20,1),'P04:InvalidServiceTime');
assertThrows(@() model(12,4,Inf,4,20,1),'P04:InvalidServiceTime');
assertThrows(@() model(12,4,[6 7],4,20,1),'P04:InvalidServiceTime');
assertThrows(@() model(12,4,1e6 + 1,4,20,1),'P04:InvalidServiceTime');
assertThrows(@() model(12,4,6,0,20,1),'P04:InvalidCapacity');
assertThrows(@() model(12,4,6,65,20,1),'P04:InvalidCapacity');
assertThrows(@() model(12,4,6,1.5,20,1),'P04:InvalidCapacity');
assertThrows(@() model(12,4,6,[4 5],20,1),'P04:InvalidCapacity');
assertThrows(@() model(12,4,6,4,0,1),'P04:InvalidDeadline');
assertThrows(@() model(12,4,6,4,Inf,1),'P04:InvalidDeadline');
assertThrows(@() model(12,4,6,4,[20 21],1),'P04:InvalidDeadline');
assertThrows(@() model(12,4,6,4,1e6 + 1,1),'P04:InvalidDeadline');
assertThrows(@() model(12,4,6,4,20,0),'P04:InvalidReleaseBatch');
assertThrows(@() model(12,4,6,4,20,9),'P04:InvalidReleaseBatch');
assertThrows(@() model(4,4,6,4,20,5),'P04:InvalidReleaseBatch');
assertThrows(@() model(12,4,6,4,20,1.5),'P04:InvalidReleaseBatch');
assertThrows(@() model(12,4,6,4,20,NaN),'P04:InvalidReleaseBatch');
assertThrows(@() model(12,4,6,4,20,[1 4]),'P04:InvalidReleaseBatch');

recovered = model(12,4,6,4,20,1);
assert(isequaln(recovered.systemLatencyMs,baseline.systemLatencyMs) && ...
    isequal(recovered.acceptedMask,baseline.acceptedMask) && ...
    recovered.onTimeCount == baseline.onTimeCount, ...
    'A valid call after malformed inputs must recover with no retained state.');

disp(['P04 checks passed: FIFO recurrence, occupancy, latency, deadline, drops, ' ...
    'two sweeps, P03 burst overflow, malformed inputs, bounds, and recovery.']);
end

function assertThrows(action,expectedIdentifier)
didThrow = false;
try
    action();
catch exception
    didThrow = true;
    assert(strcmp(exception.identifier,expectedIdentifier), ...
        'Expected %s but received %s.',expectedIdentifier,exception.identifier);
end
assert(didThrow,'Expected error %s was not thrown.',expectedIdentifier);
end
