function run_checks
%RUN_CHECKS Independent deterministic checks for the P06 exchange model.

baseline = model(100,7,4,4,2);
defaulted = model();
expectedTrueEventTimeMs = [100 104 106 110]';
expectedTrueEventElapsedMs = [0 4 6 10]';
expectedTimestampMs = [100 111 113 110]';

assert(isequal(defaulted.timestampObservationMs, ...
        baseline.timestampObservationMs) && ...
    defaulted.estimatedClockOffsetMs == baseline.estimatedClockOffsetMs && ...
    defaulted.estimatedNetworkRoundTripDelayMs == ...
        baseline.estimatedNetworkRoundTripDelayMs, ...
    'No-argument defaults must reproduce the displayed baseline.');
assert(isequal(baseline.trueEventTimeMs,expectedTrueEventTimeMs) && ...
    isequal(baseline.trueEventElapsedMs,expectedTrueEventElapsedMs), ...
    'Baseline true event times changed.');
assert(baseline.t1ClientTransmitMs == 100 && ...
    baseline.t2ServerReceiveMs == 111 && ...
    baseline.t3ServerTransmitMs == 113 && ...
    baseline.t4ClientReceiveMs == 110 && ...
    isequal(baseline.timestampObservationMs,expectedTimestampMs), ...
    'Baseline four-timestamp observations changed.');
assert(baseline.forwardOffsetTermMs == 11 && ...
    baseline.reverseOffsetTermMs == 3 && ...
    baseline.estimatedClockOffsetMs == 7 && ...
    baseline.clockOffsetErrorMs == 0, ...
    'Baseline signed offset terms or estimate changed.');
assert(baseline.clientElapsedMs == 10 && ...
    baseline.serverResidenceMs == 2 && ...
    baseline.rawEstimatedNetworkRoundTripDelayMs == 8 && ...
    baseline.estimatedNetworkRoundTripDelayMs == 8 && ...
    baseline.trueNetworkRoundTripDelayMs == 8 && ...
    baseline.estimatedSymmetricOneWayDelayMs == 4 && ...
    baseline.trueMeanOneWayDelayMs == 4, ...
    'Baseline elapsed, residence, or round-trip arithmetic changed.');
assert(baseline.pathAsymmetryMs == 0 && ...
    baseline.expectedOffsetEstimateMs == 7 && ...
    baseline.forwardDelayInferenceErrorMs == 0 && ...
    baseline.reverseDelayInferenceErrorMs == 0, ...
    'Baseline symmetric-delay inference changed.');
assert(baseline.offsetIdentityResidualMs == 0 && ...
    baseline.roundTripIdentityResidualMs == 0 && ...
    baseline.rawRoundTripIdentityResidualMs == 0 && ...
    baseline.responseIdentityResidualMs == 0 && ...
    baseline.processingCancellationResidualMs == 0, ...
    'Baseline governing identities must close exactly.');
assert(~baseline.roundTripNormalizationApplied && ...
    baseline.rawRoundTripWithinNumericalTolerance, ...
    'The baseline must not require round-trip numerical normalization.');
assert(baseline.pathSymmetrySatisfiedInTruth && ...
    baseline.clockOffsetUnbiasedInTruth && ...
    strcmp(baseline.exchangeState,'symmetric-unbiased'), ...
    'Baseline truth-only symmetry state changed.');
assert(baseline.pathSymmetryRequiredForUnbiasedOffset && ...
    ~baseline.pathSymmetryGenerallyObservableFromOneExchange && ...
    ~baseline.timestampObservationsGenerallyUniqueToPhysicalTruth && ...
    baseline.serverProcessingRemovedFromNetworkRoundTrip, ...
    'The symmetry and processing interpretation boundary changed.');
assert(baseline.truthAvailableForTeachingOnly && ...
    baseline.clientClockIsReference && ...
    baseline.serverClockRateMatchesClient && baseline.twoWayExchangeModeled && ...
    ~baseline.fullNtpProtocolModeled && ~baseline.multipleExchangesModeled && ...
    ~baseline.clockFilterModeled, ...
    'The analytical exchange scope flags changed.');
assert(~baseline.clockSkewModeled && ~baseline.timestampNoiseModeled && ...
    ~baseline.packetLossModeled && ~baseline.hardwareTimestampingModeled && ...
    ~baseline.networkIoPerformed && ~baseline.clockAdjustmentPerformed, ...
    'The clock, timestamp, network, and hardware claim boundary changed.');
assert(~baseline.timeoutModeled && ~baseline.cancellationModeled && ...
    ~baseline.actualWaitPerformed, ...
    'The finite model must not imply timeout, cancellation, or wall-clock waits.');

repeated = model(100,7,4,4,2);
assert(isequal(repeated.trueEventTimeMs,baseline.trueEventTimeMs) && ...
    isequal(repeated.timestampObservationMs,baseline.timestampObservationMs) && ...
    repeated.estimatedClockOffsetMs == baseline.estimatedClockOffsetMs && ...
    repeated.estimatedNetworkRoundTripDelayMs == ...
        baseline.estimatedNetworkRoundTripDelayMs, ...
    'Identical inputs must reproduce the complete deterministic exchange.');
shifted = model(500,7,4,4,2);
assert(isequal(shifted.trueEventTimeMs,baseline.trueEventTimeMs + 400) && ...
    isequal(shifted.timestampObservationMs, ...
        baseline.timestampObservationMs + 400) && ...
    shifted.estimatedClockOffsetMs == baseline.estimatedClockOffsetMs && ...
    shifted.estimatedNetworkRoundTripDelayMs == ...
        baseline.estimatedNetworkRoundTripDelayMs, ...
    'A common time-origin shift must not change derived intervals.');
typed = model(uint8(100),int8(7),uint8(4),uint8(4),uint8(2));
assert(isequal(typed.timestampObservationMs,baseline.timestampObservationMs) && ...
    typed.estimatedClockOffsetMs == baseline.estimatedClockOffsetMs && ...
    typed.estimatedNetworkRoundTripDelayMs == ...
        baseline.estimatedNetworkRoundTripDelayMs, ...
    'Accepted integer-class inputs must normalize to baseline arithmetic.');
fractional = model(100.5,-0.5,1.25,1.25,0.75);
assert(fractional.estimatedClockOffsetMs == -0.5 && ...
    fractional.estimatedNetworkRoundTripDelayMs == 2.5 && ...
    fractional.clientElapsedMs == 3.25 && ...
    fractional.serverResidenceMs == 0.75 && ...
    fractional.pathSymmetrySatisfiedInTruth, ...
    'Finite fractional inputs must preserve symmetric exchange arithmetic.');

clockOffsetsMs = [-8 0 12];
for index = 1:numel(clockOffsetsMs)
    swept = model(100,clockOffsetsMs(index),4,4,2);
    assert(swept.estimatedClockOffsetMs == clockOffsetsMs(index) && ...
        swept.clockOffsetErrorMs == 0, ...
        'Symmetric offset sweep estimate changed.');
    assert(swept.estimatedNetworkRoundTripDelayMs == 8 && ...
        swept.clientElapsedMs == 10 && swept.serverResidenceMs == 2, ...
        'Clock offset must not change same-clock elapsed intervals.');
end

symmetricOneWayDelaysMs = [1 4 10];
expectedRoundTripMs = [2 8 20];
expectedClientElapsedMs = [4 10 22];
for index = 1:numel(symmetricOneWayDelaysMs)
    delayMs = symmetricOneWayDelaysMs(index);
    swept = model(100,7,delayMs,delayMs,2);
    assert(swept.estimatedClockOffsetMs == 7 && ...
        swept.clockOffsetErrorMs == 0, ...
        'Symmetric delay must cancel from the offset estimate.');
    assert(swept.estimatedNetworkRoundTripDelayMs == ...
            expectedRoundTripMs(index) && ...
        swept.clientElapsedMs == expectedClientElapsedMs(index) && ...
        swept.estimatedSymmetricOneWayDelayMs == delayMs, ...
        'Symmetric-delay sweep round-trip arithmetic changed.');
end

zeroPath = model(100,7,0,0,9);
assert(isequal(zeroPath.timestampObservationMs,[100 107 116 109]') && ...
    zeroPath.estimatedClockOffsetMs == 7 && ...
    zeroPath.estimatedNetworkRoundTripDelayMs == 0 && ...
    zeroPath.clientElapsedMs == zeroPath.serverResidenceMs && ...
    zeroPath.processingCancellationResidualMs == 0, ...
    'Zero network delay must leave only removable server residence.');
assert(zeroPath.zeroNetworkRoundTripLimitInTruth && ...
    ~zeroPath.pathSymmetryGenerallyObservableFromOneExchange && ...
    ~zeroPath.timestampObservationsGenerallyUniqueToPhysicalTruth, ...
    'The truth-only zero-RTT exception must not overstate general observability.');
processingTimesMs = [0 2 12];
expectedProcessingElapsedMs = [8 10 20];
for index = 1:numel(processingTimesMs)
    swept = model(100,7,4,4,processingTimesMs(index));
    assert(swept.serverResidenceMs == processingTimesMs(index) && ...
        swept.clientElapsedMs == expectedProcessingElapsedMs(index), ...
        'Server residence must change raw response elapsed time.');
    assert(swept.estimatedClockOffsetMs == 7 && ...
        swept.estimatedNetworkRoundTripDelayMs == 8 && ...
        swept.processingCancellationResidualMs == 0, ...
        'Server residence must cancel from offset and network round-trip estimates.');
end
zeroOffsetAsymmetric = model(100,0,7,1,2);
assert(zeroOffsetAsymmetric.estimatedClockOffsetMs == 3 && ...
    zeroOffsetAsymmetric.clockOffsetErrorMs == 3 && ...
    ~zeroOffsetAsymmetric.pathSymmetrySatisfiedInTruth, ...
    'Zero true offset must still expose asymmetry bias.');
forwardDominant = model(100,7,7,1,2);
reverseDominant = model(100,7,1,7,2);
assert(forwardDominant.clockOffsetErrorMs == 3 && ...
    reverseDominant.clockOffsetErrorMs == -3 && ...
    forwardDominant.estimatedNetworkRoundTripDelayMs == 8 && ...
    reverseDominant.estimatedNetworkRoundTripDelayMs == 8, ...
    'Swapping path directions must flip offset-error sign without changing round trip.');
nearToleranceAsymmetry = model(100,7,4 + 1e-12,4,2);
assert(~nearToleranceAsymmetry.pathSymmetrySatisfiedInTruth && ...
    ~nearToleranceAsymmetry.clockOffsetUnbiasedInTruth && ...
    strcmp(nearToleranceAsymmetry.exchangeState,'asymmetric-offset-bias'), ...
    'Near-tolerance asymmetry must produce one consistent truth classification.');
tinyAsymmetryAtZeroOrigin = model(0,0,1e-10,0,0);
tinyAsymmetryAtShiftedOrigin = model(1e6,0,1e-10,0,0);
assert(~tinyAsymmetryAtZeroOrigin.pathSymmetrySatisfiedInTruth && ...
    ~tinyAsymmetryAtShiftedOrigin.pathSymmetrySatisfiedInTruth && ...
    ~tinyAsymmetryAtZeroOrigin.clockOffsetUnbiasedInTruth && ...
    ~tinyAsymmetryAtShiftedOrigin.clockOffsetUnbiasedInTruth && ...
    tinyAsymmetryAtZeroOrigin.truthClassificationUsesExactInputs && ...
    tinyAsymmetryAtShiftedOrigin.truthClassificationUsesExactInputs, ...
    'Truth symmetry classification must not depend on absolute time origin.');
cancellationEdge = model(-1e6,-1e6,1e-10,0,1e-6);
assert(cancellationEdge.rawEstimatedNetworkRoundTripDelayMs < 0 && ...
    cancellationEdge.roundTripNormalizationApplied && ...
    cancellationEdge.rawRoundTripWithinNumericalTolerance, ...
    'The retained cancellation edge must expose its tiny negative raw RTT.');
assert(cancellationEdge.estimatedNetworkRoundTripDelayMs == 0 && ...
    cancellationEdge.estimatedSymmetricOneWayDelayMs == 0 && ...
    cancellationEdge.trueNetworkRoundTripDelayMs == 1e-10 && ...
    abs(cancellationEdge.roundTripIdentityResidualMs) <= ...
        cancellationEdge.comparisonToleranceMs && ...
    abs(cancellationEdge.rawRoundTripIdentityResidualMs) <= ...
        cancellationEdge.comparisonToleranceMs, ...
    'The physical RTT estimate must normalize to zero within numerical tolerance.');
precisionObscuredZeroTruth = model(-1e6,-1e6,0,0,1e-10);
assert(precisionObscuredZeroTruth.zeroNetworkRoundTripLimitInTruth && ...
    ~precisionObscuredZeroTruth.pathSymmetryGenerallyObservableFromOneExchange && ...
    ~precisionObscuredZeroTruth.timestampObservationsGenerallyUniqueToPhysicalTruth, ...
    'The exact zero-delay truth must remain separate from general observability claims.');
assert(precisionObscuredZeroTruth.rawEstimatedNetworkRoundTripDelayMs > 0 && ...
    precisionObscuredZeroTruth.trueNetworkRoundTripDelayMs == 0 && ...
    abs(precisionObscuredZeroTruth.rawRoundTripIdentityResidualMs) <= ...
        precisionObscuredZeroTruth.comparisonToleranceMs, ...
    'The retained precision edge must show how represented intervals can obscure zero truth.');
zeroEverything = model(0,0,0,0,0);
assert(all(zeroEverything.trueEventTimeMs == 0) && ...
    all(zeroEverything.timestampObservationMs == 0) && ...
    zeroEverything.estimatedClockOffsetMs == 0 && ...
    zeroEverything.estimatedNetworkRoundTripDelayMs == 0, ...
    'The all-zero limit must remain exactly zero.');
negativeOffset = model(100,-20,4,4,2);
assert(negativeOffset.estimatedClockOffsetMs == -20 && ...
    negativeOffset.clockOffsetErrorMs == 0 && ...
    negativeOffset.pathSymmetrySatisfiedInTruth, ...
    'A negative signed clock offset must remain valid under symmetry.');

broken = model(100,7,7,1,2);
aliased = model(100,10,4,4,2);
expectedAliasTimestampMs = [100 114 116 110]';
assert(isequal(broken.timestampObservationMs,expectedAliasTimestampMs) && ...
    isequal(aliased.timestampObservationMs,expectedAliasTimestampMs), ...
    'The asymmetric truth and symmetric offset alias must expose identical timestamps.');
assert(broken.clockOffsetMs ~= aliased.clockOffsetMs && ...
    broken.forwardDelayMs ~= aliased.forwardDelayMs && ...
    broken.reverseDelayMs ~= aliased.reverseDelayMs, ...
    'The exact timestamp aliases must retain distinct physical truths.');
assert(broken.pathAsymmetryMs == 6 && ...
    broken.estimatedClockOffsetMs == 10 && ...
    broken.clockOffsetErrorMs == 3 && ...
    broken.estimatedNetworkRoundTripDelayMs == 8 && ...
    broken.estimatedSymmetricOneWayDelayMs == 4, ...
    'The broken case must assign half the path asymmetry to offset.');
assert(broken.forwardDelayInferenceErrorMs == -3 && ...
    broken.reverseDelayInferenceErrorMs == 3 && ...
    ~broken.pathSymmetrySatisfiedInTruth && ...
    strcmp(broken.exchangeState,'asymmetric-offset-bias'), ...
    'The broken directional-delay inference or truth state changed.');
assert(aliased.clockOffsetErrorMs == 0 && ...
    aliased.pathSymmetrySatisfiedInTruth && ...
    strcmp(aliased.exchangeState,'symmetric-unbiased'), ...
    'The symmetric alias must remain a distinct unbiased truth.');
assert(broken.offsetIdentityResidualMs == 0 && ...
    broken.roundTripIdentityResidualMs == 0 && ...
    broken.responseIdentityResidualMs == 0 && ...
    broken.processingCancellationResidualMs == 0, ...
    'Perfect identities must coexist with broken path symmetry.');

bounded = model(1e6,1e6,1e6,1e6,1e6);
assert(numel(bounded.timestampObservationMs) == 4 && ...
    all(isfinite(bounded.trueEventTimeMs)) && ...
    all(isfinite(bounded.timestampObservationMs)) && ...
    max(abs(bounded.timestampObservationMs)) <= ...
        bounded.maxDerivedTimestampMagnitudeMs, ...
    'The maximum-magnitude valid exchange must remain finite and bounded.');
assert(bounded.estimatedClockOffsetMs == 1e6 && ...
    bounded.estimatedNetworkRoundTripDelayMs == 2e6 && ...
    bounded.timestampCount == 4 && bounded.maxTimestampCount == 4 && ...
    bounded.maxTimeMagnitudeMs == 1e6 && ...
    bounded.maxDerivedTimestampMagnitudeMs == 4e6 && ...
    bounded.calculationBounded, ...
    'The numerical and fixed-work resource bounds changed.');
assert(abs(bounded.offsetIdentityResidualMs) <= ...
        bounded.comparisonToleranceMs && ...
    abs(bounded.roundTripIdentityResidualMs) <= ...
        bounded.comparisonToleranceMs && ...
    abs(bounded.processingCancellationResidualMs) <= ...
        bounded.comparisonToleranceMs, ...
    'Maximum-magnitude identities exceeded the declared tolerance.');
boundedNegative = model(-1e6,-1e6,1e6,1e6,1e6);
assert(all(isfinite(boundedNegative.timestampObservationMs)) && ...
    boundedNegative.estimatedClockOffsetMs == -1e6 && ...
    boundedNegative.estimatedNetworkRoundTripDelayMs == 2e6, ...
    'The negative time-origin and offset bound must remain finite.');

assertThrows(@() model([],7,4,4,2),'P06:InvalidClientSendTime');
assertThrows(@() model('100',7,4,4,2),'P06:InvalidClientSendTime');
assertThrows(@() model([100 101],7,4,4,2),'P06:InvalidClientSendTime');
assertThrows(@() model(100 + 1i,7,4,4,2),'P06:InvalidClientSendTime');
assertThrows(@() model(NaN,7,4,4,2),'P06:InvalidClientSendTime');
assertThrows(@() model(Inf,7,4,4,2),'P06:InvalidClientSendTime');
assertThrows(@() model(1e6 + 1,7,4,4,2),'P06:InvalidClientSendTime');
assertThrows(@() model(-1e6 - 1,7,4,4,2),'P06:InvalidClientSendTime');

assertThrows(@() model(100,[],4,4,2),'P06:InvalidClockOffset');
assertThrows(@() model(100,'7',4,4,2),'P06:InvalidClockOffset');
assertThrows(@() model(100,[7 8],4,4,2),'P06:InvalidClockOffset');
assertThrows(@() model(100,7 + 1i,4,4,2),'P06:InvalidClockOffset');
assertThrows(@() model(100,NaN,4,4,2),'P06:InvalidClockOffset');
assertThrows(@() model(100,Inf,4,4,2),'P06:InvalidClockOffset');
assertThrows(@() model(100,1e6 + 1,4,4,2),'P06:InvalidClockOffset');
assertThrows(@() model(100,-1e6 - 1,4,4,2),'P06:InvalidClockOffset');

assertThrows(@() model(100,7,[],4,2),'P06:InvalidForwardDelay');
assertThrows(@() model(100,7,'4',4,2),'P06:InvalidForwardDelay');
assertThrows(@() model(100,7,[4 5],4,2),'P06:InvalidForwardDelay');
assertThrows(@() model(100,7,4 + 1i,4,2),'P06:InvalidForwardDelay');
assertThrows(@() model(100,7,NaN,4,2),'P06:InvalidForwardDelay');
assertThrows(@() model(100,7,Inf,4,2),'P06:InvalidForwardDelay');
assertThrows(@() model(100,7,-1,4,2),'P06:InvalidForwardDelay');
assertThrows(@() model(100,7,1e6 + 1,4,2),'P06:InvalidForwardDelay');

assertThrows(@() model(100,7,4,[],2),'P06:InvalidReverseDelay');
assertThrows(@() model(100,7,4,'4',2),'P06:InvalidReverseDelay');
assertThrows(@() model(100,7,4,[4 5],2),'P06:InvalidReverseDelay');
assertThrows(@() model(100,7,4,4 + 1i,2),'P06:InvalidReverseDelay');
assertThrows(@() model(100,7,4,NaN,2),'P06:InvalidReverseDelay');
assertThrows(@() model(100,7,4,Inf,2),'P06:InvalidReverseDelay');
assertThrows(@() model(100,7,4,-1,2),'P06:InvalidReverseDelay');
assertThrows(@() model(100,7,4,1e6 + 1,2),'P06:InvalidReverseDelay');

assertThrows(@() model(100,7,4,4,[]),'P06:InvalidServerProcessing');
assertThrows(@() model(100,7,4,4,'2'),'P06:InvalidServerProcessing');
assertThrows(@() model(100,7,4,4,[2 3]),'P06:InvalidServerProcessing');
assertThrows(@() model(100,7,4,4,2 + 1i),'P06:InvalidServerProcessing');
assertThrows(@() model(100,7,4,4,NaN),'P06:InvalidServerProcessing');
assertThrows(@() model(100,7,4,4,Inf),'P06:InvalidServerProcessing');
assertThrows(@() model(100,7,4,4,-1),'P06:InvalidServerProcessing');
assertThrows(@() model(100,7,4,4,1e6 + 1),'P06:InvalidServerProcessing');

recovered = model(100,7,4,4,2);
assert(isequal(recovered.trueEventTimeMs,baseline.trueEventTimeMs) && ...
    isequal(recovered.timestampObservationMs,baseline.timestampObservationMs) && ...
    recovered.estimatedClockOffsetMs == baseline.estimatedClockOffsetMs && ...
    recovered.estimatedNetworkRoundTripDelayMs == ...
        baseline.estimatedNetworkRoundTripDelayMs, ...
    'A valid call after malformed inputs must recover with no retained state.');

disp(['P06 checks passed: four timestamps, offset and round-trip equations, two sweeps, ' ...
    'asymmetry alias, processing cancellation, malformed inputs, bounds, and recovery.']);
end

function assertThrows(action,expectedIdentifier)
didThrow = false;
try
    action();
catch exception
    didThrow = true;
    assert(strcmp(exception.identifier,expectedIdentifier), ...
        'Expected %s but received %s.',expectedIdentifier,exception.identifier);
end
assert(didThrow,'Expected error %s was not thrown.',expectedIdentifier);
end
