function out = model(messageCount,messagePeriodMs,pathDelayMs,lostMessageIndex,retransmissionTimeoutMs,deadlineMs)
%MODEL Compare bounded UDP datagrams with a TCP byte-stream recovery path.
%   One P02 application frame is the visible teaching record. The model is
%   an analytical timeout path, not a socket, packet trace, or full TCP stack.

if nargin < 1
    messageCount = 6;
end
if nargin < 2
    messagePeriodMs = 200;
end
if nargin < 3
    pathDelayMs = 20;
end
if nargin < 4
    lostMessageIndex = 3;
end
if nargin < 5
    retransmissionTimeoutMs = 1000;
end
if nargin < 6
    deadlineMs = 800;
end

if ~(isnumeric(messageCount) && isreal(messageCount) && isscalar(messageCount) && ...
        isfinite(messageCount) && messageCount == fix(messageCount) && ...
        messageCount >= 1 && messageCount <= 64)
    error('P03:InvalidMessageCount', ...
        'messageCount must be a finite integer from 1 through 64.');
end
if ~(isnumeric(messagePeriodMs) && isreal(messagePeriodMs) && ...
        isscalar(messagePeriodMs) && isfinite(messagePeriodMs) && ...
        messagePeriodMs >= 1 && messagePeriodMs <= 1e6)
    error('P03:InvalidMessagePeriod', ...
        'messagePeriodMs must be finite and in the range 1 through 1e6 ms.');
end
if ~(isnumeric(pathDelayMs) && isreal(pathDelayMs) && isscalar(pathDelayMs) && ...
        isfinite(pathDelayMs) && pathDelayMs >= 0 && pathDelayMs <= 1e6)
    error('P03:InvalidPathDelay', ...
        'pathDelayMs must be finite and in the range 0 through 1e6 ms.');
end

% Normalize accepted integer classes before dependent range checks and
% arithmetic so valid values cannot saturate in their input class.
messageCount = double(messageCount);
messagePeriodMs = double(messagePeriodMs);
pathDelayMs = double(pathDelayMs);

if ~(isnumeric(lostMessageIndex) && isreal(lostMessageIndex) && ...
        isscalar(lostMessageIndex) && isfinite(lostMessageIndex) && ...
        lostMessageIndex == fix(lostMessageIndex) && ...
        lostMessageIndex >= 0 && lostMessageIndex <= messageCount)
    error('P03:InvalidLostMessageIndex', ...
        'lostMessageIndex must be zero or a record index within messageCount.');
end
if ~(isnumeric(retransmissionTimeoutMs) && isreal(retransmissionTimeoutMs) && ...
        isscalar(retransmissionTimeoutMs) && isfinite(retransmissionTimeoutMs) && ...
        retransmissionTimeoutMs >= 1000 && retransmissionTimeoutMs <= 1e6)
    error('P03:InvalidRetransmissionTimeout', ...
        'retransmissionTimeoutMs must be finite and in the range 1000 through 1e6 ms.');
end
if ~(isnumeric(deadlineMs) && isreal(deadlineMs) && isscalar(deadlineMs) && ...
        isfinite(deadlineMs) && deadlineMs >= 0.001 && deadlineMs <= 1e6)
    error('P03:InvalidDeadline', ...
        'deadlineMs must be finite and in the range 0.001 through 1e6 ms.');
end

lostMessageIndex = double(lostMessageIndex);
retransmissionTimeoutMs = double(retransmissionTimeoutMs);
deadlineMs = double(deadlineMs);

maxRecordCount = 64;
applicationFrameBytes = 15;
linkRateKbps = 1000;
serializationTimeMs = 8 * applicationFrameBytes / linkRateKbps;
serviceDelayMs = pathDelayMs + serializationTimeMs;

recordIndex = (1:messageCount)';
sendTimeMs = (recordIndex - 1) * messagePeriodMs;
lostMask = false(messageCount,1);
if lostMessageIndex > 0
    lostMask(lostMessageIndex) = true;
end

% Calculate application ages in relative time. This avoids losing deadline
% precision when a small service delay is subtracted from a large send time.
baseArrivalTimeMs = sendTimeMs + serviceDelayMs;
udpLatencyMs = serviceDelayMs * ones(messageCount,1);
udpLatencyMs(lostMask) = NaN;
udpDeliveryTimeMs = sendTimeMs + udpLatencyMs;

% The teaching TCP path assumes one successful retransmission after the
% controlled timeout. It also assumes a sender window large enough to admit
% every modeled range and a receiver that retains later out-of-order bytes.
% The application receives only a contiguous prefix.
tcpNetworkAgeMs = serviceDelayMs * ones(messageCount,1);
if lostMessageIndex > 0
    tcpNetworkAgeMs(lostMask) = retransmissionTimeoutMs + serviceDelayMs;
end
deadlineToleranceMs = 1e-9;
tcpLatencyMs = zeros(messageCount,1);
priorApplicationAgeMs = -Inf;
for index = 1:messageCount
    priorAgeAtThisSendMs = priorApplicationAgeMs - messagePeriodMs;
    if priorAgeAtThisSendMs > tcpNetworkAgeMs(index) + deadlineToleranceMs
        tcpLatencyMs(index) = priorAgeAtThisSendMs;
    else
        tcpLatencyMs(index) = tcpNetworkAgeMs(index);
    end
    priorApplicationAgeMs = tcpLatencyMs(index);
end
tcpNetworkArrivalTimeMs = sendTimeMs + tcpNetworkAgeMs;
tcpApplicationDeliveryTimeMs = sendTimeMs + tcpLatencyMs;
tcpHeadOfLineDelayMs = max(tcpLatencyMs - tcpNetworkAgeMs,0);
tcpHeadOfLineDelayMs(tcpHeadOfLineDelayMs <= deadlineToleranceMs) = 0;
tcpOutOfOrderBufferedMask = tcpHeadOfLineDelayMs > 0;

tcpOnTime = tcpLatencyMs <= deadlineMs + deadlineToleranceMs;
udpDelivered = isfinite(udpLatencyMs);
udpOnTime = udpDelivered & udpLatencyMs <= deadlineMs + deadlineToleranceMs;
tcpRetransmissionCount = double(lostMessageIndex > 0);
tcpTimeoutCount = tcpRetransmissionCount;

receivedUdpLatencyMs = udpLatencyMs(udpDelivered);
if isempty(receivedUdpLatencyMs)
    maxUdpLatencyMs = NaN;
else
    maxUdpLatencyMs = max(receivedUdpLatencyMs);
end

if lostMessageIndex > 0
    tcpState = 'recovered-after-timeout';
    udpState = 'delivered-with-gap';
else
    tcpState = 'no-loss';
    udpState = 'no-loss';
end

% Deliberately broken boundary assumption. These are the exact P02 baseline
% frame bytes, repeated twice. A TCP byte-stream API may return the stream as
% 9 and 21 bytes. The bounded parser below retains bytes, reads P02's sync and
% declared length, enforces P02's 135-byte policy, and checks the checksum.
p02Frame = uint8([126,0,11,42,18,52,255,106,255,206,0,50,0,150,135]);
tcpStreamBytes = uint8([p02Frame,p02Frame]);
frameWriteBytes = [numel(p02Frame),numel(p02Frame)];
tcpReadChunkBytes = [9,21];
udpDatagramReadBytes = frameWriteBytes;
naiveTcpFramesRecovered = sum(tcpReadChunkBytes == applicationFrameBytes);
bufferedParser = parseP02Chunks(tcpStreamBytes,tcpReadChunkBytes,135,2);

partialHeaderParser = parseP02Chunks(p02Frame(1:2),[2],135,2);
badSyncParser = parseP02Chunks(uint8([125,0,11]),[3],135,2);
overLimitHeaderBytes = uint8([126,0,133]);
overLimitParser = parseP02Chunks(overLimitHeaderBytes,[3],135,2);
corruptP02Frame = p02Frame;
corruptP02Frame(8) = bitxor(corruptP02Frame(8),uint8(1));
corruptParser = parseP02Chunks(corruptP02Frame,[15],135,2);
recoveryParser = parseP02Chunks(tcpStreamBytes,tcpReadChunkBytes,135,2);
threeFrameStream = uint8([p02Frame,p02Frame,p02Frame]);
frameLimitParser = parseP02Chunks(threeFrameStream,[15,15,15],135,2);

udpFramesRecovered = sum(udpDatagramReadBytes == applicationFrameBytes);
boundaryCase = struct( ...
    'p02FrameBytes',p02Frame, ...
    'frameWriteBytes',frameWriteBytes, ...
    'tcpReadChunkBytes',tcpReadChunkBytes, ...
    'udpDatagramReadBytes',udpDatagramReadBytes, ...
    'naiveTcpFramesRecovered',naiveTcpFramesRecovered, ...
    'bufferedTcpFramesRecovered',bufferedParser.framesRecovered, ...
    'bufferedTcpFrameLengths',bufferedParser.frameLengths, ...
    'bufferedTcpRemainderBytes',bufferedParser.remainderBytes, ...
    'bufferedTcpBufferBytesAfterRead',bufferedParser.bufferBytesAfterRead, ...
    'bufferedTcpMaxBufferObservedBytes',bufferedParser.maxBufferObservedBytes, ...
    'bufferedTcpParserState',bufferedParser.state, ...
    'bufferedTcpSyncChecks',bufferedParser.syncChecks, ...
    'bufferedTcpLengthChecks',bufferedParser.lengthChecks, ...
    'bufferedTcpChecksumChecks',bufferedParser.checksumChecks, ...
    'partialHeaderParser',partialHeaderParser, ...
    'badSyncParser',badSyncParser, ...
    'overLimitHeaderBytes',overLimitHeaderBytes, ...
    'overLimitParser',overLimitParser, ...
    'corruptParser',corruptParser, ...
    'recoveryParser',recoveryParser, ...
    'frameLimitParser',frameLimitParser, ...
    'udpFramesRecovered',udpFramesRecovered, ...
    'tcpPreservesMessageBoundaries',false, ...
    'udpPreservesDatagramBoundariesInCase',true, ...
    'maxParserFrameBytes',135, ...
    'maxParserFrameCount',2, ...
    'maxParserStreamBytes',270);

out = struct( ...
    'messageCount',messageCount, ...
    'messagePeriodMs',messagePeriodMs, ...
    'pathDelayMs',pathDelayMs, ...
    'lostMessageIndex',lostMessageIndex, ...
    'retransmissionTimeoutMs',retransmissionTimeoutMs, ...
    'deadlineMs',deadlineMs, ...
    'deadlineToleranceMs',deadlineToleranceMs, ...
    'applicationFrameBytes',applicationFrameBytes, ...
    'linkRateKbps',linkRateKbps, ...
    'serializationTimeMs',serializationTimeMs, ...
    'serviceDelayMs',serviceDelayMs, ...
    'recordIndex',recordIndex, ...
    'sendTimeMs',sendTimeMs, ...
    'baseArrivalTimeMs',baseArrivalTimeMs, ...
    'lostMask',lostMask, ...
    'udpDeliveryTimeMs',udpDeliveryTimeMs, ...
    'udpLatencyMs',udpLatencyMs, ...
    'udpDelivered',udpDelivered, ...
    'udpOnTime',udpOnTime, ...
    'udpDeliveredCount',sum(udpDelivered), ...
    'udpOnTimeCount',sum(udpOnTime), ...
    'udpLostCount',sum(lostMask), ...
    'udpLateDeliveredCount',sum(udpDelivered & ~udpOnTime), ...
    'maxUdpLatencyMs',maxUdpLatencyMs, ...
    'udpState',udpState, ...
    'tcpNetworkAgeMs',tcpNetworkAgeMs, ...
    'tcpNetworkArrivalTimeMs',tcpNetworkArrivalTimeMs, ...
    'tcpApplicationDeliveryTimeMs',tcpApplicationDeliveryTimeMs, ...
    'tcpLatencyMs',tcpLatencyMs, ...
    'tcpHeadOfLineDelayMs',tcpHeadOfLineDelayMs, ...
    'tcpHeadOfLineBlockedCount',sum(tcpOutOfOrderBufferedMask), ...
    'tcpOutOfOrderBufferedMask',tcpOutOfOrderBufferedMask, ...
    'tcpOutOfOrderBufferedRecordCount',sum(tcpOutOfOrderBufferedMask), ...
    'tcpOutOfOrderBufferedApplicationBytes', ...
        applicationFrameBytes * sum(tcpOutOfOrderBufferedMask), ...
    'maxTcpHeadOfLineDelayMs',max(tcpHeadOfLineDelayMs), ...
    'maxTcpLatencyMs',max(tcpLatencyMs), ...
    'tcpOnTime',tcpOnTime, ...
    'tcpDeliveredCount',messageCount, ...
    'tcpOnTimeCount',sum(tcpOnTime), ...
    'tcpLateCount',sum(~tcpOnTime), ...
    'tcpRetransmissionCount',tcpRetransmissionCount, ...
    'tcpTimeoutCount',tcpTimeoutCount, ...
    'tcpState',tcpState, ...
    'tcpRecordRangeAttemptCount',messageCount + tcpRetransmissionCount, ...
    'udpDatagramAttemptCount',messageCount, ...
    'maxRecordCount',maxRecordCount, ...
    'maxTcpRecordRangeAttemptCount',maxRecordCount + 1, ...
    'maxTcpOutOfOrderBufferedRecordCount',maxRecordCount - 1, ...
    'maxTcpOutOfOrderBufferedApplicationBytes', ...
        applicationFrameBytes * (maxRecordCount - 1), ...
    'sufficientSenderWindowAssumed',true, ...
    'outOfOrderReceiverRetentionAssumed',true, ...
    'analyticalTimeoutOnly',true, ...
    'actualWaitPerformed',false, ...
    'deadlineOnlyClassifies',true, ...
    'cancellationModeled',false, ...
    'boundaryCase',boundaryCase);
end

function result = parseP02Chunks(streamBytes,chunkSizes,maxFrameBytes,maxFrameCount)
%PARSEP02CHUNKS Bounded incremental parser for the transparent P02 frame.
maxStreamBytes = maxFrameBytes * maxFrameCount;
if ~(isa(streamBytes,'uint8') && isrow(streamBytes) && ...
        isnumeric(chunkSizes) && isreal(chunkSizes) && isvector(chunkSizes) && ...
        all(isfinite(chunkSizes)) && all(chunkSizes == fix(chunkSizes)) && ...
        all(chunkSizes >= 1) && sum(chunkSizes) == numel(streamBytes) && ...
        numel(streamBytes) <= maxStreamBytes)
    error('P03:InternalParserFixture', ...
        'Parser fixtures must be uint8 rows within the fixed stream and chunk bounds.');
end
syncByte = uint8(126);
minimumPayloadBytes = 3;
maximumPayloadBytes = maxFrameBytes - 4;
receiveBuffer = zeros(1,0,'uint8');
frameLengths = zeros(1,maxFrameCount);
bufferBytesAfterRead = NaN(size(chunkSizes));
nextByte = 1;
framesRecovered = 0;
syncChecks = 0;
lengthChecks = 0;
checksumChecks = 0;
maxBufferObservedBytes = 0;
parserState = 'complete';

for chunkIndex = 1:numel(chunkSizes)
    if strncmp(parserState,'rejected-',9)
        break
    end
    chunkEnd = nextByte + chunkSizes(chunkIndex) - 1;
    receiveBuffer = [receiveBuffer,streamBytes(nextByte:chunkEnd)]; %#ok<AGROW>
    nextByte = chunkEnd + 1;
    maxBufferObservedBytes = max(maxBufferObservedBytes,numel(receiveBuffer));

    for parseAttempt = 1:maxFrameCount
        if framesRecovered >= maxFrameCount
            parserState = 'rejected-frame-limit';
            break
        end
        if numel(receiveBuffer) < 3
            break
        end

        syncChecks = syncChecks + 1;
        if receiveBuffer(1) ~= syncByte
            parserState = 'rejected-sync';
            break
        end

        lengthChecks = lengthChecks + 1;
        declaredPayloadBytes = 256 * double(receiveBuffer(2)) + ...
            double(receiveBuffer(3));
        expectedFrameBytes = declaredPayloadBytes + 4;
        schemaValid = declaredPayloadBytes >= minimumPayloadBytes && ...
            mod(declaredPayloadBytes - minimumPayloadBytes,2) == 0;
        if ~schemaValid || declaredPayloadBytes > maximumPayloadBytes
            parserState = 'rejected-length';
            break
        end
        if numel(receiveBuffer) < expectedFrameBytes
            parserState = 'waiting-for-frame';
            break
        end

        checksumChecks = checksumChecks + 1;
        candidate = receiveBuffer(1:expectedFrameBytes);
        if mod(sum(double(candidate(2:end))),256) ~= 0
            parserState = 'rejected-checksum';
            break
        end

        framesRecovered = framesRecovered + 1;
        frameLengths(framesRecovered) = expectedFrameBytes;
        receiveBuffer = receiveBuffer(expectedFrameBytes + 1:end);
        parserState = 'complete';
        if framesRecovered >= maxFrameCount
            break
        end
    end
    if framesRecovered >= maxFrameCount && ...
            (~isempty(receiveBuffer) || nextByte <= numel(streamBytes))
        parserState = 'rejected-frame-limit';
    end
    bufferBytesAfterRead(chunkIndex) = numel(receiveBuffer);
end

if ~strncmp(parserState,'rejected-',9) && ~isempty(receiveBuffer)
    parserState = 'waiting-for-frame';
end

result = struct( ...
    'framesRecovered',framesRecovered, ...
    'frameLengths',frameLengths(1:framesRecovered), ...
    'remainderBytes',numel(receiveBuffer), ...
    'unconsumedStreamBytes',max(numel(streamBytes) - nextByte + 1,0), ...
    'unrecoveredBytes',numel(receiveBuffer) + ...
        max(numel(streamBytes) - nextByte + 1,0), ...
    'bufferBytesAfterRead',bufferBytesAfterRead, ...
    'maxBufferObservedBytes',maxBufferObservedBytes, ...
    'syncChecks',syncChecks, ...
    'lengthChecks',lengthChecks, ...
    'checksumChecks',checksumChecks, ...
    'state',parserState);
end
