function run_checks
%RUN_CHECKS Independent deterministic checks for the P03 transport model.

baseline = model(6,200,20,3,1000,800);
defaulted = model();
expectedSend = [0 200 400 600 800 1000]';
expectedBaseArrival = [20.12 220.12 420.12 620.12 820.12 1020.12]';
expectedUdpDelivery = [20.12 220.12 NaN 620.12 820.12 1020.12]';
expectedTcpNetwork = [20.12 220.12 1420.12 620.12 820.12 1020.12]';
expectedTcpApplication = [20.12 220.12 1420.12 1420.12 1420.12 1420.12]';
expectedTcpLatency = [20.12 20.12 1020.12 820.12 620.12 420.12]';
expectedTcpHol = [0 0 0 800 600 400]';

assert(isequaln(defaulted.udpDeliveryTimeMs,baseline.udpDeliveryTimeMs) && ...
    isequal(defaulted.tcpApplicationDeliveryTimeMs, ...
        baseline.tcpApplicationDeliveryTimeMs) && ...
    defaulted.deadlineMs == baseline.deadlineMs, ...
    'No-argument defaults must reproduce the displayed baseline.');

assert(abs(baseline.serializationTimeMs - 0.120) < 1e-12, ...
    'A 15-byte P02 frame at 1000 kb/s must serialize in 0.120 ms.');
assert(abs(baseline.serviceDelayMs - 20.12) < 1e-12, ...
    'Baseline service delay must be path plus P02 serialization.');
assert(isequal(baseline.sendTimeMs,expectedSend),'Baseline send times changed.');
assert(max(abs(baseline.baseArrivalTimeMs - expectedBaseArrival)) < 1e-9, ...
    'Baseline no-loss arrival times changed.');
assert(isequaln(baseline.udpDeliveryTimeMs,expectedUdpDelivery), ...
    'UDP must leave one visible datagram gap and deliver later records.');
assert(max(abs(baseline.tcpNetworkArrivalTimeMs - expectedTcpNetwork)) < 1e-9, ...
    'TCP timeout/retransmission arrival changed.');
assert(max(abs(baseline.tcpApplicationDeliveryTimeMs - expectedTcpApplication)) < 1e-9, ...
    'TCP contiguous-prefix delivery changed.');
assert(max(abs(baseline.tcpLatencyMs - expectedTcpLatency)) < 1e-9, ...
    'TCP application ages changed.');
assert(max(abs(baseline.tcpHeadOfLineDelayMs - expectedTcpHol)) < 1e-9, ...
    'TCP head-of-line waits changed.');
assert(baseline.tcpDeliveredCount == 6 && baseline.tcpOnTimeCount == 4, ...
    'TCP baseline must deliver six eventually and four on time.');
assert(baseline.udpDeliveredCount == 5 && baseline.udpOnTimeCount == 5, ...
    'UDP baseline must deliver five records, all on time.');
assert(baseline.tcpRetransmissionCount == 1 && baseline.tcpTimeoutCount == 1, ...
    'The controlled TCP loss must cause one timeout and one retransmission.');
assert(baseline.tcpHeadOfLineBlockedCount == 3 && ...
    abs(baseline.maxTcpHeadOfLineDelayMs - 800) < 1e-12, ...
    'Records 4 through 6 must wait behind the recovered range.');
assert(baseline.sufficientSenderWindowAssumed && ...
    baseline.outOfOrderReceiverRetentionAssumed && ...
    baseline.tcpOutOfOrderBufferedRecordCount == 3 && ...
    baseline.tcpOutOfOrderBufferedApplicationBytes == 45, ...
    'Baseline recovery requires three retained ranges totaling 45 application bytes.');
assert(strcmp(baseline.tcpState,'recovered-after-timeout') && ...
    strcmp(baseline.udpState,'delivered-with-gap'), ...
    'Baseline transport states changed.');
assert(baseline.analyticalTimeoutOnly && ~baseline.actualWaitPerformed && ...
    baseline.deadlineOnlyClassifies && ~baseline.cancellationModeled, ...
    'Timeout/deadline claim boundaries must remain explicit.');

boundary = baseline.boundaryCase;
expectedP02Frame = uint8([126 0 11 42 18 52 255 106 255 206 0 50 0 150 135]);
assert(isequal(boundary.p02FrameBytes,expectedP02Frame), ...
    'The parser fixture must use P02 baseline bytes exactly.');
assert(isequal(boundary.frameWriteBytes,[15 15]),'P02 frame writes must remain 15 bytes each.');
assert(isequal(boundary.tcpReadChunkBytes,[9 21]), ...
    'The deterministic TCP read split must preserve all 30 stream bytes.');
assert(sum(boundary.frameWriteBytes) == sum(boundary.tcpReadChunkBytes), ...
    'TCP read chunks must neither create nor lose stream bytes.');
assert(boundary.naiveTcpFramesRecovered == 0 && ...
    boundary.bufferedTcpFramesRecovered == 2 && ...
    isequal(boundary.bufferedTcpFrameLengths,[15 15]) && ...
    boundary.bufferedTcpRemainderBytes == 0 && ...
    isequal(boundary.bufferedTcpBufferBytesAfterRead,[9 0]), ...
    'Length-aware buffering must recover both frames where the naive parser fails.');
assert(strcmp(boundary.bufferedTcpParserState,'complete') && ...
    boundary.bufferedTcpSyncChecks == 3 && boundary.bufferedTcpLengthChecks == 3 && ...
    boundary.bufferedTcpChecksumChecks == 2, ...
    'The bounded parser must inspect sync and length before validating two checksums.');
assert(boundary.partialHeaderParser.framesRecovered == 0 && ...
    boundary.partialHeaderParser.remainderBytes == 2 && ...
    strcmp(boundary.partialHeaderParser.state,'waiting-for-frame'), ...
    'A partial P02 header must remain buffered without being accepted.');
assert(boundary.badSyncParser.framesRecovered == 0 && ...
    boundary.badSyncParser.syncChecks == 1 && ...
    boundary.badSyncParser.lengthChecks == 0 && ...
    strcmp(boundary.badSyncParser.state,'rejected-sync'), ...
    'A malformed sync byte must reject before reading a declared length.');
overLimitDeclaredPayload = 256 * double(boundary.overLimitHeaderBytes(2)) + ...
    double(boundary.overLimitHeaderBytes(3));
assert(mod(overLimitDeclaredPayload - 3,2) == 0 && ...
    overLimitDeclaredPayload > 131, ...
    'The over-limit fixture must remain schema-valid and isolate the size policy.');
assert(boundary.overLimitParser.framesRecovered == 0 && ...
    boundary.overLimitParser.checksumChecks == 0 && ...
    strcmp(boundary.overLimitParser.state,'rejected-length'), ...
    'An over-policy P02 length must reject before checksum evaluation.');
assert(boundary.corruptParser.framesRecovered == 0 && ...
    boundary.corruptParser.checksumChecks == 1 && ...
    strcmp(boundary.corruptParser.state,'rejected-checksum'), ...
    'A corrupt complete P02 frame must fail its checksum.');
assert(boundary.recoveryParser.framesRecovered == 2 && ...
    boundary.recoveryParser.remainderBytes == 0 && ...
    strcmp(boundary.recoveryParser.state,'complete'), ...
    'A valid parse after malformed fixtures must recover with no retained parser state.');
assert(boundary.frameLimitParser.framesRecovered == 2 && ...
    boundary.frameLimitParser.unconsumedStreamBytes == 15 && ...
    boundary.frameLimitParser.unrecoveredBytes == 15 && ...
    strcmp(boundary.frameLimitParser.state,'rejected-frame-limit'), ...
    'A third valid frame must stop at the global two-frame parser bound.');
assert(boundary.udpFramesRecovered == 2 && ...
    isequal(boundary.udpDatagramReadBytes,[15 15]), ...
    'The adequate-buffer UDP case must retain two datagram boundaries.');
assert(~boundary.tcpPreservesMessageBoundaries && ...
    boundary.udpPreservesDatagramBoundariesInCase, ...
    'TCP byte-stream and UDP datagram boundary semantics changed.');

repeated = model(6,200,20,3,1000,800);
assert(isequaln(repeated.udpDeliveryTimeMs,baseline.udpDeliveryTimeMs) && ...
    isequal(repeated.tcpApplicationDeliveryTimeMs,baseline.tcpApplicationDeliveryTimeMs) && ...
    isequal(repeated.boundaryCase.tcpReadChunkBytes,boundary.tcpReadChunkBytes), ...
    'Identical inputs must reproduce every deterministic timeline.');

typed = model(uint8(6),uint16(200),uint8(20),uint8(3),uint16(1000),uint16(800));
assert(isequaln(typed.udpDeliveryTimeMs,baseline.udpDeliveryTimeMs) && ...
    isequal(typed.tcpApplicationDeliveryTimeMs,baseline.tcpApplicationDeliveryTimeMs), ...
    'Accepted integer-class scalars must normalize to baseline arithmetic.');

minimum = model(1,1,0,1,1000,1);
assert(minimum.tcpDeliveredCount == 1 && minimum.udpDeliveredCount == 0 && ...
    minimum.udpLostCount == 1 && isnan(minimum.maxUdpLatencyMs), ...
    'The one-record sole-loss case must exercise an empty UDP delivery set.');
assert(minimum.tcpRecordRangeAttemptCount == 2 && ...
    minimum.udpDatagramAttemptCount == 1, ...
    'The minimum loss case has two modeled TCP range attempts and one UDP attempt.');

noLoss = model(6,200,20,0,1000,800);
assert(isequal(noLoss.tcpApplicationDeliveryTimeMs,noLoss.udpDeliveryTimeMs), ...
    'Without loss, the isolated TCP and UDP timing paths must match.');
assert(noLoss.tcpDeliveredCount == 6 && noLoss.udpDeliveredCount == 6 && ...
    noLoss.tcpOnTimeCount == 6 && noLoss.udpOnTimeCount == 6, ...
    'No-loss limit must deliver every record on time.');
assert(noLoss.tcpRetransmissionCount == 0 && noLoss.tcpTimeoutCount == 0 && ...
    noLoss.tcpHeadOfLineBlockedCount == 0 && noLoss.maxTcpHeadOfLineDelayMs == 0, ...
    'No-loss limit must have no recovery or head-of-line penalty.');
assert(strcmp(noLoss.tcpState,'no-loss') && strcmp(noLoss.udpState,'no-loss'), ...
    'No-loss states changed.');

lastLost = model(6,200,20,6,1000,800);
assert(lastLost.tcpRetransmissionCount == 1 && lastLost.udpLostCount == 1, ...
    'Last-record loss must still distinguish TCP recovery from a UDP gap.');
assert(lastLost.tcpHeadOfLineBlockedCount == 0 && lastLost.maxTcpHeadOfLineDelayMs == 0, ...
    'No later byte range exists to wait behind a lost final record.');
assert(abs(lastLost.tcpApplicationDeliveryTimeMs(end) - 2020.12) < 1e-9 && ...
    lastLost.tcpDeliveredCount == 6 && lastLost.udpDeliveredCount == 5, ...
    'The final lost record must recover exactly once at 2020.12 ms.');

deadlineEqual = model(6,200,20,0,1000,noLoss.serviceDelayMs);
deadlineBelow = model(6,200,20,0,1000,noLoss.serviceDelayMs - 0.001);
assert(deadlineEqual.tcpOnTimeCount == 6 && deadlineEqual.udpOnTimeCount == 6, ...
    'Delivery exactly at the deadline must count as on time.');
assert(deadlineBelow.tcpOnTimeCount == 0 && deadlineBelow.udpOnTimeCount == 0, ...
    'A deadline below fixed service time must reject every record as late.');
assert(isequal(deadlineEqual.tcpApplicationDeliveryTimeMs, ...
    deadlineBelow.tcpApplicationDeliveryTimeMs) && ...
    isequal(deadlineEqual.udpDeliveryTimeMs,deadlineBelow.udpDeliveryTimeMs), ...
    'Changing a deadline must classify, never alter, transport delivery.');

largeTimestampBoundary = model(64,1e6,20,0,1000,20.12);
assert(largeTimestampBoundary.tcpOnTimeCount == 64 && ...
    largeTimestampBoundary.udpOnTimeCount == 64 && ...
    max(abs(largeTimestampBoundary.tcpLatencyMs - 20.12)) < 1e-12 && ...
    max(abs(largeTimestampBoundary.udpLatencyMs - 20.12)) < 1e-12, ...
    'Relative-age arithmetic must preserve exact-deadline classification at large send times.');

coincidentArrival = model(2,1e6,999999,1,1e6,1e6);
assert(coincidentArrival.tcpHeadOfLineBlockedCount == 0 && ...
    coincidentArrival.maxTcpHeadOfLineDelayMs == 0 && ...
    coincidentArrival.tcpOutOfOrderBufferedApplicationBytes == 0 && ...
    coincidentArrival.tcpApplicationDeliveryTimeMs(2) == ...
        coincidentArrival.tcpNetworkArrivalTimeMs(2), ...
    'Numerically coincident arrivals must not create artificial buffered data.');

messagePeriods = [100 200 400];
expectedPeriodTcpOnTime = [3 4 5];
expectedPeriodUdpOnTime = [5 5 5];
expectedPeriodMaxHol = [900 800 600];
actualPeriodTcpOnTime = zeros(size(messagePeriods));
actualPeriodUdpOnTime = zeros(size(messagePeriods));
actualPeriodMaxHol = zeros(size(messagePeriods));
for index = 1:numel(messagePeriods)
    swept = model(6,messagePeriods(index),20,3,1000,800);
    actualPeriodTcpOnTime(index) = swept.tcpOnTimeCount;
    actualPeriodUdpOnTime(index) = swept.udpOnTimeCount;
    actualPeriodMaxHol(index) = swept.maxTcpHeadOfLineDelayMs;
end
assert(isequal(actualPeriodTcpOnTime,expectedPeriodTcpOnTime), ...
    'Application-period sweep TCP deadline counts changed.');
assert(isequal(actualPeriodUdpOnTime,expectedPeriodUdpOnTime), ...
    'Application-period sweep must not change UDP deadline counts.');
assert(max(abs(actualPeriodMaxHol - expectedPeriodMaxHol)) < 1e-12, ...
    'Application-period sweep head-of-line values changed.');

retransmissionTimeouts = [1000 1250 1500];
expectedTimeoutTcpOnTime = [4 3 2];
expectedTimeoutUdpOnTime = [5 5 5];
expectedTimeoutMaxAge = [1020.12 1270.12 1520.12];
actualTimeoutTcpOnTime = zeros(size(retransmissionTimeouts));
actualTimeoutUdpOnTime = zeros(size(retransmissionTimeouts));
actualTimeoutMaxAge = zeros(size(retransmissionTimeouts));
for index = 1:numel(retransmissionTimeouts)
    swept = model(6,200,20,3,retransmissionTimeouts(index),800);
    actualTimeoutTcpOnTime(index) = swept.tcpOnTimeCount;
    actualTimeoutUdpOnTime(index) = swept.udpOnTimeCount;
    actualTimeoutMaxAge(index) = swept.maxTcpLatencyMs;
end
assert(isequal(actualTimeoutTcpOnTime,expectedTimeoutTcpOnTime), ...
    'Retransmission-timeout sweep TCP deadline counts changed.');
assert(isequal(actualTimeoutUdpOnTime,expectedTimeoutUdpOnTime), ...
    'TCP timeout must not change UDP deadline counts.');
assert(max(abs(actualTimeoutMaxAge - expectedTimeoutMaxAge)) < 1e-9, ...
    'Retransmission-timeout sweep maximum ages changed.');

bounded = model(64,1,0,32,1000,2000);
assert(numel(bounded.recordIndex) == 64 && bounded.maxRecordCount == 64, ...
    'The resource-bound case must model exactly 64 records.');
assert(bounded.tcpRecordRangeAttemptCount == 65 && ...
    bounded.maxTcpRecordRangeAttemptCount == 65 && ...
    bounded.udpDatagramAttemptCount == 64, ...
    'The single-loss model must cap modeled range attempts at 65 and datagram attempts at 64.');
assert(bounded.tcpOutOfOrderBufferedRecordCount <= ...
    bounded.maxTcpOutOfOrderBufferedRecordCount && ...
    bounded.tcpOutOfOrderBufferedApplicationBytes <= ...
        bounded.maxTcpOutOfOrderBufferedApplicationBytes && ...
    bounded.maxTcpOutOfOrderBufferedApplicationBytes == 945, ...
    'Retained out-of-order application data must remain within the explicit 945-byte bound.');
typedBounded = model(uint8(64),uint32(1),uint8(0),uint8(32), ...
    uint32(1000),uint16(2000));
assert(typedBounded.messageCount == 64 && ...
    typedBounded.tcpRecordRangeAttemptCount == bounded.tcpRecordRangeAttemptCount && ...
    typedBounded.tcpOutOfOrderBufferedApplicationBytes == ...
        bounded.tcpOutOfOrderBufferedApplicationBytes, ...
    'Typed inputs at the resource bound must normalize without saturation.');

assertThrows(@() model(0,200,20,0,1000,800),'P03:InvalidMessageCount');
assertThrows(@() model(65,200,20,0,1000,800),'P03:InvalidMessageCount');
assertThrows(@() model(1.5,200,20,0,1000,800),'P03:InvalidMessageCount');
assertThrows(@() model(NaN,200,20,0,1000,800),'P03:InvalidMessageCount');
assertThrows(@() model([6 7],200,20,0,1000,800),'P03:InvalidMessageCount');
assertThrows(@() model(1 + 1i,200,20,0,1000,800),'P03:InvalidMessageCount');
assertThrows(@() model(6,0,20,0,1000,800),'P03:InvalidMessagePeriod');
assertThrows(@() model(6,Inf,20,0,1000,800),'P03:InvalidMessagePeriod');
assertThrows(@() model(6,[100 200],20,0,1000,800),'P03:InvalidMessagePeriod');
assertThrows(@() model(6,1e6 + 1,20,0,1000,800),'P03:InvalidMessagePeriod');
assertThrows(@() model(6,200,-1,0,1000,800),'P03:InvalidPathDelay');
assertThrows(@() model(6,200,Inf,0,1000,800),'P03:InvalidPathDelay');
assertThrows(@() model(6,200,[20 21],0,1000,800),'P03:InvalidPathDelay');
assertThrows(@() model(6,200,1e6 + 1,0,1000,800),'P03:InvalidPathDelay');
assertThrows(@() model(6,200,20,-1,1000,800),'P03:InvalidLostMessageIndex');
assertThrows(@() model(6,200,20,7,1000,800),'P03:InvalidLostMessageIndex');
assertThrows(@() model(6,200,20,1.5,1000,800),'P03:InvalidLostMessageIndex');
assertThrows(@() model(6,200,20,NaN,1000,800),'P03:InvalidLostMessageIndex');
assertThrows(@() model(6,200,20,[0 1],1000,800),'P03:InvalidLostMessageIndex');
assertThrows(@() model(6,200,20,0,0,800),'P03:InvalidRetransmissionTimeout');
assertThrows(@() model(6,200,20,0,999,800),'P03:InvalidRetransmissionTimeout');
assertThrows(@() model(6,200,20,0,Inf,800),'P03:InvalidRetransmissionTimeout');
assertThrows(@() model(6,200,20,0,[1000 1250],800),'P03:InvalidRetransmissionTimeout');
assertThrows(@() model(6,200,20,0,1e6 + 1,800),'P03:InvalidRetransmissionTimeout');
assertThrows(@() model(6,200,20,0,1000,0),'P03:InvalidDeadline');
assertThrows(@() model(6,200,20,0,1000,Inf),'P03:InvalidDeadline');
assertThrows(@() model(6,200,20,0,1000,[800 900]),'P03:InvalidDeadline');
assertThrows(@() model(6,200,20,0,1000,1e6 + 1),'P03:InvalidDeadline');

recovered = model(6,200,20,3,1000,800);
assert(isequaln(recovered.udpDeliveryTimeMs,baseline.udpDeliveryTimeMs) && ...
    isequal(recovered.tcpApplicationDeliveryTimeMs,baseline.tcpApplicationDeliveryTimeMs) && ...
    recovered.tcpOnTimeCount == baseline.tcpOnTimeCount, ...
    'A valid call after malformed inputs must recover with no retained state.');

disp(['P03 checks passed: transport timelines, timeout, head-of-line blocking, deadlines, ' ...
    'stream framing, malformed inputs, bounds, and recovery.']);
end

function assertThrows(action,expectedIdentifier)
didThrow = false;
try
    action();
catch exception
    didThrow = true;
    assert(strcmp(exception.identifier,expectedIdentifier), ...
        'Expected %s but received %s.',expectedIdentifier,exception.identifier);
end
assert(didThrow,'Expected error %s was not thrown.',expectedIdentifier);
end
