function out = model(startTimeNs,clockOffsetNs,forwardDelayNs,reverseDelayNs, ...
    followerTurnaroundNs,hostLatencyScale,hardwareTickNs,calibrationFraction)
%MODEL Deterministic timestamp-placement model for the P07 lesson.
% clockOffsetNs is follower clock minus leader clock. The analytical
% hardware timestamps are captured near a modeled wire reference plane;
% no NIC, PHC, packet exchange, or physical clock is accessed.

if nargin < 1
    startTimeNs = 100000;
end
if nargin < 2
    clockOffsetNs = 120;
end
if nargin < 3
    forwardDelayNs = 800;
end
if nargin < 4
    reverseDelayNs = 800;
end
if nargin < 5
    followerTurnaroundNs = 4000;
end
if nargin < 6
    hostLatencyScale = 1;
end
if nargin < 7
    hardwareTickNs = 8;
end
if nargin < 8
    calibrationFraction = 1;
end

maxTimeMagnitudeNs = 1e6;
maxHostLatencyScale = 4;
minimumHardwareTickNs = 0.125;
maxHardwareTickNs = 1024;
maxCalibrationFraction = 2;
exchangeCount = 8;
timestampsPerExchange = 4;
maxTimestampCount = exchangeCount * timestampsPerExchange;
maxDerivedTimestampMagnitudeNs = 6e6;

if ~(isnumeric(startTimeNs) && isreal(startTimeNs) && ...
        isscalar(startTimeNs) && isfinite(startTimeNs) && ...
        startTimeNs >= -maxTimeMagnitudeNs && ...
        startTimeNs <= maxTimeMagnitudeNs)
    error('P07:InvalidStartTime', ...
        'startTimeNs must be a finite scalar from %.0f through %.0f ns.', ...
        -maxTimeMagnitudeNs,maxTimeMagnitudeNs);
end
if ~(isnumeric(clockOffsetNs) && isreal(clockOffsetNs) && ...
        isscalar(clockOffsetNs) && isfinite(clockOffsetNs) && ...
        clockOffsetNs >= -maxTimeMagnitudeNs && ...
        clockOffsetNs <= maxTimeMagnitudeNs)
    error('P07:InvalidClockOffset', ...
        'clockOffsetNs must be a finite scalar from %.0f through %.0f ns.', ...
        -maxTimeMagnitudeNs,maxTimeMagnitudeNs);
end
if ~(isnumeric(forwardDelayNs) && isreal(forwardDelayNs) && ...
        isscalar(forwardDelayNs) && isfinite(forwardDelayNs) && ...
        forwardDelayNs >= 0 && forwardDelayNs <= maxTimeMagnitudeNs)
    error('P07:InvalidForwardDelay', ...
        'forwardDelayNs must be a finite scalar from 0 through %.0f ns.', ...
        maxTimeMagnitudeNs);
end
if ~(isnumeric(reverseDelayNs) && isreal(reverseDelayNs) && ...
        isscalar(reverseDelayNs) && isfinite(reverseDelayNs) && ...
        reverseDelayNs >= 0 && reverseDelayNs <= maxTimeMagnitudeNs)
    error('P07:InvalidReverseDelay', ...
        'reverseDelayNs must be a finite scalar from 0 through %.0f ns.', ...
        maxTimeMagnitudeNs);
end
if ~(isnumeric(followerTurnaroundNs) && isreal(followerTurnaroundNs) && ...
        isscalar(followerTurnaroundNs) && isfinite(followerTurnaroundNs) && ...
        followerTurnaroundNs >= 0 && ...
        followerTurnaroundNs <= maxTimeMagnitudeNs)
    error('P07:InvalidFollowerTurnaround', ...
        'followerTurnaroundNs must be a finite scalar from 0 through %.0f ns.', ...
        maxTimeMagnitudeNs);
end
if ~(isnumeric(hostLatencyScale) && isreal(hostLatencyScale) && ...
        isscalar(hostLatencyScale) && isfinite(hostLatencyScale) && ...
        hostLatencyScale >= 0 && hostLatencyScale <= maxHostLatencyScale)
    error('P07:InvalidHostLatencyScale', ...
        'hostLatencyScale must be a finite scalar from 0 through %.0f.', ...
        maxHostLatencyScale);
end
if ~(isnumeric(hardwareTickNs) && isreal(hardwareTickNs) && ...
        isscalar(hardwareTickNs) && isfinite(hardwareTickNs) && ...
        hardwareTickNs >= minimumHardwareTickNs && ...
        hardwareTickNs <= maxHardwareTickNs)
    error('P07:InvalidHardwareTick', ...
        'hardwareTickNs must be a finite scalar from %.3g through %.0f ns.', ...
        minimumHardwareTickNs,maxHardwareTickNs);
end
if ~(isnumeric(calibrationFraction) && isreal(calibrationFraction) && ...
        isscalar(calibrationFraction) && isfinite(calibrationFraction) && ...
        calibrationFraction >= 0 && ...
        calibrationFraction <= maxCalibrationFraction)
    error('P07:InvalidCalibrationFraction', ...
        'calibrationFraction must be a finite scalar from 0 through %.0f.', ...
        maxCalibrationFraction);
end

startTimeNs = double(startTimeNs);
clockOffsetNs = double(clockOffsetNs);
forwardDelayNs = double(forwardDelayNs);
reverseDelayNs = double(reverseDelayNs);
followerTurnaroundNs = double(followerTurnaroundNs);
hostLatencyScale = double(hostLatencyScale);
hardwareTickNs = double(hardwareTickNs);
calibrationFraction = double(calibrationFraction);

exchangePeriodNs = 20003;
exchangeIndex = 1:exchangeCount;
exchangeStartTimeNs = startTimeNs + (exchangeIndex - 1) * exchangePeriodNs;

% Simulation truth uses the leader clock as the reference. T1 is the
% leader Sync transmit event, T2 is follower receive, T3 is follower
% Delay_Req transmit, and T4 is leader receive.
trueEventTimeNs = [exchangeStartTimeNs; ...
    exchangeStartTimeNs + forwardDelayNs; ...
    exchangeStartTimeNs + forwardDelayNs + followerTurnaroundNs; ...
    exchangeStartTimeNs + forwardDelayNs + followerTurnaroundNs + ...
        reverseDelayNs];
trueEventElapsedNs = trueEventTimeNs - ...
    repmat(exchangeStartTimeNs,timestampsPerExchange,1);
idealReferencePlaneTimestampNs = trueEventTimeNs;
idealReferencePlaneTimestampNs(2:3,:) = ...
    idealReferencePlaneTimestampNs(2:3,:) + clockOffsetNs;

% Software capture is modeled before each transmit reaches the wire and
% after each receive leaves the wire. The fixed pattern is deterministic;
% hostLatencyScale changes only this host-path placement.
softwareBaseLatencyNs = [600;800;500;700];
softwareVariationUnitNs = 100;
softwareLatencyShape = [ ...
    0 1 2 1 3 1 4 2; ...
    1 3 0 4 1 2 3 0; ...
    2 0 3 1 4 2 1 3; ...
    0 2 1 3 0 4 2 1];
softwareHostLatencyNs = hostLatencyScale * ...
    (repmat(softwareBaseLatencyNs,1,exchangeCount) + ...
    softwareVariationUnitNs * softwareLatencyShape);
softwareTimestampPlacementErrorNs = [ ...
    -softwareHostLatencyNs(1,:);softwareHostLatencyNs(2,:); ...
    -softwareHostLatencyNs(3,:);softwareHostLatencyNs(4,:)];
softwareTimestampNs = idealReferencePlaneTimestampNs + ...
    softwareTimestampPlacementErrorNs;

% The four hardware pipeline offsets are a transparent teaching fixture,
% not device specifications. TX timestamps precede the reference plane;
% RX timestamps follow it. Egress correction is added and ingress
% correction is subtracted after the raw timestamp is quantized.
hardwarePipelineOffsetNs = [-20;80;-20;20];
hardwareFullCorrectionNs = -hardwarePipelineOffsetNs;
rawHardwareTimestampNs = idealReferencePlaneTimestampNs + ...
    repmat(hardwarePipelineOffsetNs,1,exchangeCount);
quantizedRawHardwareTimestampNs = hardwareTickNs * ...
    round(rawHardwareTimestampNs / hardwareTickNs);
hardwareQuantizationErrorNs = quantizedRawHardwareTimestampNs - ...
    rawHardwareTimestampNs;
configuredHardwareCorrectionNs = calibrationFraction * ...
    repmat(hardwareFullCorrectionNs,1,exchangeCount);
hardwareTimestampNs = quantizedRawHardwareTimestampNs + ...
    configuredHardwareCorrectionNs;
hardwareCalibrationResidualNs = ...
    repmat(hardwarePipelineOffsetNs,1,exchangeCount) + ...
    configuredHardwareCorrectionNs;
hardwareTimestampErrorNs = hardwareTimestampNs - ...
    idealReferencePlaneTimestampNs;

idealForwardOffsetTermNs = idealReferencePlaneTimestampNs(2,:) - ...
    idealReferencePlaneTimestampNs(1,:);
idealReverseOffsetTermNs = idealReferencePlaneTimestampNs(3,:) - ...
    idealReferencePlaneTimestampNs(4,:);
idealEstimatedClockOffsetNs = ...
    (idealForwardOffsetTermNs + idealReverseOffsetTermNs) / 2;
idealEstimatedRoundTripDelayNs = ...
    (idealReferencePlaneTimestampNs(4,:) - ...
    idealReferencePlaneTimestampNs(1,:)) - ...
    (idealReferencePlaneTimestampNs(3,:) - ...
    idealReferencePlaneTimestampNs(2,:));

softwareForwardOffsetTermNs = softwareTimestampNs(2,:) - ...
    softwareTimestampNs(1,:);
softwareReverseOffsetTermNs = softwareTimestampNs(3,:) - ...
    softwareTimestampNs(4,:);
softwareEstimatedClockOffsetNs = ...
    (softwareForwardOffsetTermNs + softwareReverseOffsetTermNs) / 2;
softwareEstimatedRoundTripDelayNs = ...
    (softwareTimestampNs(4,:) - softwareTimestampNs(1,:)) - ...
    (softwareTimestampNs(3,:) - softwareTimestampNs(2,:));

hardwareForwardOffsetTermNs = hardwareTimestampNs(2,:) - ...
    hardwareTimestampNs(1,:);
hardwareReverseOffsetTermNs = hardwareTimestampNs(3,:) - ...
    hardwareTimestampNs(4,:);
hardwareEstimatedClockOffsetNs = ...
    (hardwareForwardOffsetTermNs + hardwareReverseOffsetTermNs) / 2;
hardwareEstimatedRoundTripDelayNs = ...
    (hardwareTimestampNs(4,:) - hardwareTimestampNs(1,:)) - ...
    (hardwareTimestampNs(3,:) - hardwareTimestampNs(2,:));

trueNetworkRoundTripDelayNs = forwardDelayNs + reverseDelayNs;
pathAsymmetryNs = forwardDelayNs - reverseDelayNs;
expectedIdealClockOffsetEstimateNs = ...
    clockOffsetNs + pathAsymmetryNs / 2;
softwarePlacementOffsetContributionNs = ...
    (softwareTimestampPlacementErrorNs(2,:) - ...
    softwareTimestampPlacementErrorNs(1,:) + ...
    softwareTimestampPlacementErrorNs(3,:) - ...
    softwareTimestampPlacementErrorNs(4,:)) / 2;
softwarePlacementRoundTripContributionNs = ...
    softwareTimestampPlacementErrorNs(4,:) - ...
    softwareTimestampPlacementErrorNs(1,:) - ...
    softwareTimestampPlacementErrorNs(3,:) + ...
    softwareTimestampPlacementErrorNs(2,:);
hardwareCalibrationOffsetContributionNs = ...
    (hardwareCalibrationResidualNs(2,:) - ...
    hardwareCalibrationResidualNs(1,:) + ...
    hardwareCalibrationResidualNs(3,:) - ...
    hardwareCalibrationResidualNs(4,:)) / 2;
hardwareCalibrationRoundTripContributionNs = ...
    hardwareCalibrationResidualNs(4,:) - ...
    hardwareCalibrationResidualNs(1,:) - ...
    hardwareCalibrationResidualNs(3,:) + ...
    hardwareCalibrationResidualNs(2,:);
hardwareQuantizationOffsetContributionNs = ...
    (hardwareQuantizationErrorNs(2,:) - ...
    hardwareQuantizationErrorNs(1,:) + ...
    hardwareQuantizationErrorNs(3,:) - ...
    hardwareQuantizationErrorNs(4,:)) / 2;
hardwareQuantizationRoundTripContributionNs = ...
    hardwareQuantizationErrorNs(4,:) - ...
    hardwareQuantizationErrorNs(1,:) - ...
    hardwareQuantizationErrorNs(3,:) + ...
    hardwareQuantizationErrorNs(2,:);

softwareClockOffsetErrorNs = ...
    softwareEstimatedClockOffsetNs - clockOffsetNs;
hardwareClockOffsetErrorNs = ...
    hardwareEstimatedClockOffsetNs - clockOffsetNs;
softwareRoundTripErrorNs = ...
    softwareEstimatedRoundTripDelayNs - trueNetworkRoundTripDelayNs;
hardwareRoundTripErrorNs = ...
    hardwareEstimatedRoundTripDelayNs - trueNetworkRoundTripDelayNs;
idealOffsetIdentityResidualNs = idealEstimatedClockOffsetNs - ...
    expectedIdealClockOffsetEstimateNs;
idealRoundTripIdentityResidualNs = idealEstimatedRoundTripDelayNs - ...
    trueNetworkRoundTripDelayNs;
softwareOffsetIdentityResidualNs = softwareEstimatedClockOffsetNs - ...
    (expectedIdealClockOffsetEstimateNs + ...
    softwarePlacementOffsetContributionNs);
softwareRoundTripIdentityResidualNs = softwareEstimatedRoundTripDelayNs - ...
    (trueNetworkRoundTripDelayNs + ...
    softwarePlacementRoundTripContributionNs);
hardwareOffsetIdentityResidualNs = hardwareEstimatedClockOffsetNs - ...
    (expectedIdealClockOffsetEstimateNs + ...
    hardwareCalibrationOffsetContributionNs + ...
    hardwareQuantizationOffsetContributionNs);
hardwareRoundTripIdentityResidualNs = hardwareEstimatedRoundTripDelayNs - ...
    (trueNetworkRoundTripDelayNs + ...
    hardwareCalibrationRoundTripContributionNs + ...
    hardwareQuantizationRoundTripContributionNs);

softwareOffsetPeakToPeakNs = max(softwareEstimatedClockOffsetNs) - ...
    min(softwareEstimatedClockOffsetNs);
hardwareOffsetPeakToPeakNs = max(hardwareEstimatedClockOffsetNs) - ...
    min(hardwareEstimatedClockOffsetNs);
softwareRoundTripPeakToPeakNs = max(softwareEstimatedRoundTripDelayNs) - ...
    min(softwareEstimatedRoundTripDelayNs);
hardwareRoundTripPeakToPeakNs = max(hardwareEstimatedRoundTripDelayNs) - ...
    min(hardwareEstimatedRoundTripDelayNs);
softwareMeanClockOffsetEstimateNs = mean(softwareEstimatedClockOffsetNs);
hardwareMeanClockOffsetEstimateNs = mean(hardwareEstimatedClockOffsetNs);
softwareMaxAbsClockOffsetErrorNs = max(abs(softwareClockOffsetErrorNs));
hardwareMaxAbsClockOffsetErrorNs = max(abs(hardwareClockOffsetErrorNs));
softwareMaxAbsRoundTripErrorNs = max(abs(softwareRoundTripErrorNs));
hardwareMaxAbsRoundTripErrorNs = max(abs(hardwareRoundTripErrorNs));

timeScaleNs = max([1;abs(idealReferencePlaneTimestampNs(:)); ...
    abs(softwareTimestampNs(:));abs(hardwareTimestampNs(:)); ...
    abs(clockOffsetNs);forwardDelayNs;reverseDelayNs;followerTurnaroundNs]);
comparisonToleranceNs = 128 * eps(timeScaleNs);
hardwareQuantizationPerStampBoundNs = hardwareTickNs / 2;
hardwareQuantizationOffsetBoundNs = hardwareTickNs;
hardwareQuantizationRoundTripBoundNs = 2 * hardwareTickNs;
hardwareQuantizationBoundSatisfied = all(abs(hardwareQuantizationErrorNs(:)) <= ...
    hardwareQuantizationPerStampBoundNs + comparisonToleranceNs);
hardwareOffsetQuantizationBoundSatisfied = ...
    all(abs(hardwareQuantizationOffsetContributionNs) <= ...
    hardwareQuantizationOffsetBoundNs + comparisonToleranceNs);
hardwareRoundTripQuantizationBoundSatisfied = ...
    all(abs(hardwareQuantizationRoundTripContributionNs) <= ...
    hardwareQuantizationRoundTripBoundNs + comparisonToleranceNs);
pathSymmetrySatisfiedInTruth = forwardDelayNs == reverseDelayNs;
hardwareCalibrationMatched = calibrationFraction == 1;
if ~hardwareCalibrationMatched
    hardwareState = 'miscalibrated-reference-plane';
elseif ~pathSymmetrySatisfiedInTruth
    hardwareState = 'calibrated-path-asymmetry-bias';
elseif hardwareTickNs > minimumHardwareTickNs
    hardwareState = 'calibrated-quantized';
else
    hardwareState = 'calibrated-fine-tick';
end

out = struct();
out.startTimeNs = startTimeNs;
out.clockOffsetNs = clockOffsetNs;
out.forwardDelayNs = forwardDelayNs;
out.reverseDelayNs = reverseDelayNs;
out.followerTurnaroundNs = followerTurnaroundNs;
out.hostLatencyScale = hostLatencyScale;
out.hardwareTickNs = hardwareTickNs;
out.calibrationFraction = calibrationFraction;
out.exchangePeriodNs = exchangePeriodNs;
out.exchangeIndex = exchangeIndex;
out.exchangeStartTimeNs = exchangeStartTimeNs;
out.trueEventTimeNs = trueEventTimeNs;
out.trueEventElapsedNs = trueEventElapsedNs;
out.idealReferencePlaneTimestampNs = idealReferencePlaneTimestampNs;
out.softwareBaseLatencyNs = softwareBaseLatencyNs;
out.softwareVariationUnitNs = softwareVariationUnitNs;
out.softwareLatencyShape = softwareLatencyShape;
out.softwareHostLatencyNs = softwareHostLatencyNs;
out.softwareTimestampPlacementErrorNs = ...
    softwareTimestampPlacementErrorNs;
out.softwareTimestampNs = softwareTimestampNs;
out.hardwarePipelineOffsetNs = hardwarePipelineOffsetNs;
out.hardwareFullCorrectionNs = hardwareFullCorrectionNs;
out.rawHardwareTimestampNs = rawHardwareTimestampNs;
out.quantizedRawHardwareTimestampNs = quantizedRawHardwareTimestampNs;
out.hardwareQuantizationErrorNs = hardwareQuantizationErrorNs;
out.configuredHardwareCorrectionNs = configuredHardwareCorrectionNs;
out.hardwareCalibrationResidualNs = hardwareCalibrationResidualNs;
out.hardwareTimestampNs = hardwareTimestampNs;
out.hardwareTimestampErrorNs = hardwareTimestampErrorNs;
out.idealForwardOffsetTermNs = idealForwardOffsetTermNs;
out.idealReverseOffsetTermNs = idealReverseOffsetTermNs;
out.idealEstimatedClockOffsetNs = idealEstimatedClockOffsetNs;
out.idealEstimatedRoundTripDelayNs = idealEstimatedRoundTripDelayNs;
out.softwareForwardOffsetTermNs = softwareForwardOffsetTermNs;
out.softwareReverseOffsetTermNs = softwareReverseOffsetTermNs;
out.softwareEstimatedClockOffsetNs = softwareEstimatedClockOffsetNs;
out.softwareEstimatedRoundTripDelayNs = ...
    softwareEstimatedRoundTripDelayNs;
out.hardwareForwardOffsetTermNs = hardwareForwardOffsetTermNs;
out.hardwareReverseOffsetTermNs = hardwareReverseOffsetTermNs;
out.hardwareEstimatedClockOffsetNs = hardwareEstimatedClockOffsetNs;
out.hardwareEstimatedRoundTripDelayNs = ...
    hardwareEstimatedRoundTripDelayNs;
out.trueNetworkRoundTripDelayNs = trueNetworkRoundTripDelayNs;
out.pathAsymmetryNs = pathAsymmetryNs;
out.expectedIdealClockOffsetEstimateNs = ...
    expectedIdealClockOffsetEstimateNs;
out.softwarePlacementOffsetContributionNs = ...
    softwarePlacementOffsetContributionNs;
out.softwarePlacementRoundTripContributionNs = ...
    softwarePlacementRoundTripContributionNs;
out.hardwareCalibrationOffsetContributionNs = ...
    hardwareCalibrationOffsetContributionNs;
out.hardwareCalibrationRoundTripContributionNs = ...
    hardwareCalibrationRoundTripContributionNs;
out.hardwareQuantizationOffsetContributionNs = ...
    hardwareQuantizationOffsetContributionNs;
out.hardwareQuantizationRoundTripContributionNs = ...
    hardwareQuantizationRoundTripContributionNs;
out.softwareClockOffsetErrorNs = softwareClockOffsetErrorNs;
out.hardwareClockOffsetErrorNs = hardwareClockOffsetErrorNs;
out.softwareRoundTripErrorNs = softwareRoundTripErrorNs;
out.hardwareRoundTripErrorNs = hardwareRoundTripErrorNs;
out.idealOffsetIdentityResidualNs = idealOffsetIdentityResidualNs;
out.idealRoundTripIdentityResidualNs = idealRoundTripIdentityResidualNs;
out.softwareOffsetIdentityResidualNs = softwareOffsetIdentityResidualNs;
out.softwareRoundTripIdentityResidualNs = softwareRoundTripIdentityResidualNs;
out.hardwareOffsetIdentityResidualNs = hardwareOffsetIdentityResidualNs;
out.hardwareRoundTripIdentityResidualNs = hardwareRoundTripIdentityResidualNs;
out.softwareOffsetPeakToPeakNs = softwareOffsetPeakToPeakNs;
out.hardwareOffsetPeakToPeakNs = hardwareOffsetPeakToPeakNs;
out.softwareRoundTripPeakToPeakNs = softwareRoundTripPeakToPeakNs;
out.hardwareRoundTripPeakToPeakNs = hardwareRoundTripPeakToPeakNs;
out.softwareMeanClockOffsetEstimateNs = softwareMeanClockOffsetEstimateNs;
out.hardwareMeanClockOffsetEstimateNs = hardwareMeanClockOffsetEstimateNs;
out.softwareMaxAbsClockOffsetErrorNs = softwareMaxAbsClockOffsetErrorNs;
out.hardwareMaxAbsClockOffsetErrorNs = hardwareMaxAbsClockOffsetErrorNs;
out.softwareMaxAbsRoundTripErrorNs = softwareMaxAbsRoundTripErrorNs;
out.hardwareMaxAbsRoundTripErrorNs = hardwareMaxAbsRoundTripErrorNs;
out.comparisonToleranceNs = comparisonToleranceNs;
out.hardwareQuantizationPerStampBoundNs = ...
    hardwareQuantizationPerStampBoundNs;
out.hardwareQuantizationOffsetBoundNs = ...
    hardwareQuantizationOffsetBoundNs;
out.hardwareQuantizationRoundTripBoundNs = ...
    hardwareQuantizationRoundTripBoundNs;
out.hardwareQuantizationBoundSatisfied = ...
    hardwareQuantizationBoundSatisfied;
out.hardwareOffsetQuantizationBoundSatisfied = ...
    hardwareOffsetQuantizationBoundSatisfied;
out.hardwareRoundTripQuantizationBoundSatisfied = ...
    hardwareRoundTripQuantizationBoundSatisfied;
out.pathSymmetrySatisfiedInTruth = pathSymmetrySatisfiedInTruth;
out.hardwareCalibrationMatched = hardwareCalibrationMatched;
out.hardwareState = hardwareState;
out.pathSymmetryRequiredForUnbiasedOffset = true;
out.consistentReferencePlaneRequired = true;
out.precisionDoesNotProveAccuracy = true;
out.truthAvailableForTeachingOnly = true;
out.leaderClockIsReference = true;
out.sameClockRateAssumed = true;
out.softwareTimestampPlacementModeled = true;
out.hardwareTimestampPlacementModeled = true;
out.roundToNearestQuantizerIsTeachingChoice = true;
out.simplifiedPtpEventSequenceModeled = true;
out.fullPtpProtocolModeled = false;
out.oneStepOrTwoStepMessagingModeled = false;
out.transparentClockCorrectionModeled = false;
out.timestampCorrelationModeled = false;
out.clockSkewModeled = false;
out.clockServoModeled = false;
out.packetLossModeled = false;
out.networkIoPerformed = false;
out.physicalHardwareUsed = false;
out.phcReadPerformed = false;
out.clockAdjustmentPerformed = false;
out.timeoutModeled = false;
out.cancellationModeled = false;
out.actualWaitPerformed = false;
out.exchangeCount = exchangeCount;
out.timestampsPerExchange = timestampsPerExchange;
out.timestampCount = numel(hardwareTimestampNs);
out.maxTimestampCount = maxTimestampCount;
out.maxTimeMagnitudeNs = maxTimeMagnitudeNs;
out.maxHostLatencyScale = maxHostLatencyScale;
out.minimumHardwareTickNs = minimumHardwareTickNs;
out.maxHardwareTickNs = maxHardwareTickNs;
out.maxCalibrationFraction = maxCalibrationFraction;
out.maxDerivedTimestampMagnitudeNs = maxDerivedTimestampMagnitudeNs;
out.calculationBounded = true;
end
