function run_checks
%RUN_CHECKS Independent deterministic checks for the P07 placement model.

baseline = model(100000,120,800,800,4000,1,8,1);
defaulted = model();
expectedElapsedNs = repmat([0;800;4800;5600],1,8);
expectedIdealFirstNs = [100000;100920;104920;105600];
expectedSoftwareOffsetNs = [170 320 120 270 220 70 420 120];
expectedHardwareOffsetNs = [118 118 122 118 122 122 118 122];
expectedSoftwareRoundTripNs = [4500 4800 4800 5100 5000 5100 5200 4800];
expectedHardwareRoundTripNs = [1596 1596 1604 1596 1604 1604 1596 1604];
expectedHardwareQuantizationErrorNs = [ ...
    4 1 -2 3 0 -3 2 -1; ...
    0 -3 2 -1 4 1 -2 3; ...
    4 1 -2 3 0 -3 2 -1; ...
    4 1 -2 3 0 -3 2 -1];

assert(isequal(defaulted.softwareTimestampNs,baseline.softwareTimestampNs) && ...
    isequal(defaulted.hardwareTimestampNs,baseline.hardwareTimestampNs) && ...
    isequal(defaulted.softwareEstimatedClockOffsetNs, ...
        baseline.softwareEstimatedClockOffsetNs) && ...
    isequal(defaulted.hardwareEstimatedClockOffsetNs, ...
        baseline.hardwareEstimatedClockOffsetNs), ...
    'No-argument defaults must reproduce the displayed baseline.');
assert(isequal(baseline.trueEventElapsedNs,expectedElapsedNs) && ...
    isequal(baseline.idealReferencePlaneTimestampNs(:,1), ...
        expectedIdealFirstNs), ...
    'Baseline true events or ideal timestamps changed.');
assert(isequal(baseline.softwareEstimatedClockOffsetNs, ...
        expectedSoftwareOffsetNs) && ...
    isequal(baseline.hardwareEstimatedClockOffsetNs, ...
        expectedHardwareOffsetNs), ...
    'Baseline software or hardware offset estimates changed.');
assert(isequal(baseline.softwareEstimatedRoundTripDelayNs, ...
        expectedSoftwareRoundTripNs) && ...
    isequal(baseline.hardwareEstimatedRoundTripDelayNs, ...
        expectedHardwareRoundTripNs) && ...
    baseline.trueNetworkRoundTripDelayNs == 1600, ...
    'Baseline round-trip estimates changed.');
assert(isequal(baseline.hardwareQuantizationErrorNs, ...
        expectedHardwareQuantizationErrorNs) && ...
    isequal(baseline.hardwareTimestampErrorNs, ...
        expectedHardwareQuantizationErrorNs), ...
    'Complete calibration must leave only the expected tick residuals.');

signedHalfTick = model(0,0,0,0,0,0,8,1);
assert(isequal(signedHalfTick.rawHardwareTimestampNs(:,1), ...
        [-20;80;-20;20]) && ...
    isequal(signedHalfTick.quantizedRawHardwareTimestampNs(:,1), ...
        [-24;80;-24;24]) && ...
    isequal(signedHalfTick.hardwareQuantizationErrorNs(:,1), ...
        [-4;0;-4;4]), ...
    'Exact positive and negative half-tick captures must round away from zero.');
assert(isequal(baseline.softwareTimestampPlacementErrorNs(:,1), ...
        [-600;900;-700;700]) && ...
    isequal(baseline.hardwareTimestampErrorNs(:,1),[4;0;4;4]), ...
    'Baseline first-exchange placement errors changed.');
assert(baseline.softwareMeanClockOffsetEstimateNs == 213.75 && ...
    baseline.softwareOffsetPeakToPeakNs == 350 && ...
    baseline.softwareMaxAbsClockOffsetErrorNs == 300 && ...
    baseline.hardwareMeanClockOffsetEstimateNs == 120 && ...
    baseline.hardwareOffsetPeakToPeakNs == 4 && ...
    baseline.hardwareMaxAbsClockOffsetErrorNs == 2, ...
    'Baseline offset precision or accuracy metrics changed.');
assert(baseline.softwareRoundTripPeakToPeakNs == 700 && ...
    baseline.softwareMaxAbsRoundTripErrorNs == 3600 && ...
    baseline.hardwareRoundTripPeakToPeakNs == 8 && ...
    baseline.hardwareMaxAbsRoundTripErrorNs == 4, ...
    'Baseline round-trip precision or accuracy metrics changed.');
assert(all(baseline.idealOffsetIdentityResidualNs == 0) && ...
    all(baseline.idealRoundTripIdentityResidualNs == 0) && ...
    all(baseline.softwareOffsetIdentityResidualNs == 0) && ...
    all(baseline.softwareRoundTripIdentityResidualNs == 0) && ...
    all(baseline.hardwareOffsetIdentityResidualNs == 0) && ...
    all(baseline.hardwareRoundTripIdentityResidualNs == 0), ...
    'Baseline error-combination identities must close exactly.');
assert(baseline.hardwareQuantizationBoundSatisfied && ...
    baseline.hardwareOffsetQuantizationBoundSatisfied && ...
    baseline.hardwareRoundTripQuantizationBoundSatisfied && ...
    baseline.hardwareQuantizationPerStampBoundNs == 4 && ...
    baseline.hardwareQuantizationOffsetBoundNs == 8 && ...
    baseline.hardwareQuantizationRoundTripBoundNs == 16, ...
    'Baseline quantization bounds changed.');
assert(baseline.pathSymmetrySatisfiedInTruth && ...
    baseline.hardwareCalibrationMatched && ...
    strcmp(baseline.hardwareState,'calibrated-quantized'), ...
    'Baseline truth-only path or calibration state changed.');

repeated = model(100000,120,800,800,4000,1,8,1);
assert(isequal(repeated.trueEventTimeNs,baseline.trueEventTimeNs) && ...
    isequal(repeated.softwareTimestampNs,baseline.softwareTimestampNs) && ...
    isequal(repeated.hardwareTimestampNs,baseline.hardwareTimestampNs) && ...
    isequal(repeated.hardwareClockOffsetErrorNs, ...
        baseline.hardwareClockOffsetErrorNs), ...
    'Identical inputs must reproduce every deterministic timestamp.');
shifted = model(108000,120,800,800,4000,1,8,1);
assert(isequal(shifted.idealReferencePlaneTimestampNs, ...
        baseline.idealReferencePlaneTimestampNs + 8000) && ...
    isequal(shifted.softwareTimestampNs,baseline.softwareTimestampNs + 8000) && ...
    isequal(shifted.hardwareTimestampNs,baseline.hardwareTimestampNs + 8000) && ...
    isequal(shifted.softwareEstimatedClockOffsetNs, ...
        baseline.softwareEstimatedClockOffsetNs) && ...
    isequal(shifted.hardwareEstimatedClockOffsetNs, ...
        baseline.hardwareEstimatedClockOffsetNs), ...
    'A tick-aligned common origin shift must preserve every interval.');
typed = model(uint32(100000),uint8(120),uint16(800),uint16(800), ...
    uint16(4000),uint8(1),uint8(8),uint8(1));
assert(isequal(typed.softwareTimestampNs,baseline.softwareTimestampNs) && ...
    isequal(typed.hardwareTimestampNs,baseline.hardwareTimestampNs), ...
    'Accepted integer numeric classes must normalize to baseline arithmetic.');
fractional = model(100.5,-0.5,1.25,1.25,10.5,0,0.5,1);
assert(all(fractional.softwareEstimatedClockOffsetNs == -0.5) && ...
    all(fractional.hardwareEstimatedClockOffsetNs == -0.25) && ...
    all(fractional.softwareEstimatedRoundTripDelayNs == 2.5) && ...
    all(fractional.hardwareEstimatedRoundTripDelayNs == 2.5), ...
    ['Finite fractional inputs must preserve software arithmetic and expose ' ...
     'the deterministic half-nanosecond hardware quantization result.']);

hostLatencyScales = [0 1 2];
expectedSoftwareRangesNs = [0 350 700];
expectedSoftwareMaxErrorsNs = [0 300 600];
expectedSoftwareRoundTripMaxErrorsNs = [0 3600 7200];
for index = 1:numel(hostLatencyScales)
    swept = model(100000,120,800,800,4000,hostLatencyScales(index),8,1);
    assert(swept.softwareOffsetPeakToPeakNs == ...
            expectedSoftwareRangesNs(index) && ...
        swept.softwareMaxAbsClockOffsetErrorNs == ...
            expectedSoftwareMaxErrorsNs(index) && ...
        swept.softwareMaxAbsRoundTripErrorNs == ...
            expectedSoftwareRoundTripMaxErrorsNs(index), ...
        'Host-path sweep software metrics changed.');
    assert(swept.hardwareOffsetPeakToPeakNs == 4 && ...
        swept.hardwareMaxAbsClockOffsetErrorNs == 2 && ...
        swept.hardwareMaxAbsRoundTripErrorNs == 4, ...
        'Host-path scale must not change near-wire hardware estimates.');
end
zeroHostPath = model(100000,120,800,800,4000,0,8,1);
assert(all(zeroHostPath.softwareTimestampPlacementErrorNs(:) == 0) && ...
    isequal(zeroHostPath.softwareTimestampNs, ...
        zeroHostPath.idealReferencePlaneTimestampNs) && ...
    all(zeroHostPath.softwareEstimatedClockOffsetNs == 120) && ...
    all(zeroHostPath.softwareEstimatedRoundTripDelayNs == 1600), ...
    'Zero host-path scale must collapse software capture to the ideal plane.');

hardwareTicksNs = [1 8 64];
expectedHardwareOffsetRangesNs = [0 4 32];
expectedHardwareMaxOffsetErrorsNs = [0 2 22];
expectedHardwareRoundTripRangesNs = [0 8 64];
expectedHardwareMaxRoundTripErrorsNs = [0 4 52];
for index = 1:numel(hardwareTicksNs)
    swept = model(100000,120,800,800,4000,1,hardwareTicksNs(index),1);
    assert(swept.hardwareOffsetPeakToPeakNs == ...
            expectedHardwareOffsetRangesNs(index) && ...
        swept.hardwareMaxAbsClockOffsetErrorNs == ...
            expectedHardwareMaxOffsetErrorsNs(index) && ...
        swept.hardwareRoundTripPeakToPeakNs == ...
            expectedHardwareRoundTripRangesNs(index) && ...
        swept.hardwareMaxAbsRoundTripErrorNs == ...
            expectedHardwareMaxRoundTripErrorsNs(index), ...
        'Hardware-tick sweep metrics changed.');
    assert(isequal(swept.softwareTimestampNs,baseline.softwareTimestampNs) && ...
        isequal(swept.softwareEstimatedClockOffsetNs, ...
            expectedSoftwareOffsetNs), ...
        'Hardware tick must not change software capture.');
    assert(swept.hardwareQuantizationBoundSatisfied && ...
        swept.hardwareOffsetQuantizationBoundSatisfied && ...
        swept.hardwareRoundTripQuantizationBoundSatisfied, ...
        'Hardware quantization exceeded a declared analytical bound.');
end
fineCalibrated = model(100000,120,800,800,4000,1,1,1);
assert(all(fineCalibrated.hardwareTimestampErrorNs(:) == 0) && ...
    all(fineCalibrated.hardwareEstimatedClockOffsetNs == 120) && ...
    all(fineCalibrated.hardwareEstimatedRoundTripDelayNs == 1600), ...
    'A 1 ns tick with exact integer fixture values and calibration must be exact.');

turnaroundValuesNs = [0 4000 10000];
for index = 1:numel(turnaroundValuesNs)
    swept = model(100000,120,800,800,turnaroundValuesNs(index),1,8,1);
    assert(isequal(swept.softwareEstimatedClockOffsetNs, ...
            baseline.softwareEstimatedClockOffsetNs) && ...
        isequal(swept.hardwareEstimatedClockOffsetNs, ...
            baseline.hardwareEstimatedClockOffsetNs) && ...
        isequal(swept.softwareEstimatedRoundTripDelayNs, ...
            baseline.softwareEstimatedRoundTripDelayNs) && ...
        isequal(swept.hardwareEstimatedRoundTripDelayNs, ...
            baseline.hardwareEstimatedRoundTripDelayNs), ...
        'Follower turnaround must cancel from offset and round-trip estimates.');
end
zeroEverything = model(0,0,0,0,0,0,1,1);
expectedZeroIdealNs = repmat(zeroEverything.exchangeStartTimeNs,4,1);
assert(isequal(zeroEverything.idealReferencePlaneTimestampNs, ...
        expectedZeroIdealNs) && ...
    all(zeroEverything.softwareEstimatedClockOffsetNs == 0) && ...
    all(zeroEverything.hardwareEstimatedClockOffsetNs == 0) && ...
    all(zeroEverything.softwareEstimatedRoundTripDelayNs == 0) && ...
    all(zeroEverything.hardwareEstimatedRoundTripDelayNs == 0), ...
    'The zero-offset, zero-path, zero-turnaround limit must remain zero.');

forwardDominant = model(100000,120,1200,400,4000,0,1,1);
reverseDominant = model(100000,120,400,1200,4000,0,1,1);
assert(all(forwardDominant.hardwareEstimatedClockOffsetNs == 520) && ...
    all(reverseDominant.hardwareEstimatedClockOffsetNs == -280) && ...
    all(forwardDominant.hardwareEstimatedRoundTripDelayNs == 1600) && ...
    all(reverseDominant.hardwareEstimatedRoundTripDelayNs == 1600), ...
    'Swapping path directions must flip inherited asymmetry bias.');
assert(forwardDominant.pathAsymmetryNs == 800 && ...
    reverseDominant.pathAsymmetryNs == -800 && ...
    ~forwardDominant.pathSymmetrySatisfiedInTruth && ...
    strcmp(forwardDominant.hardwareState, ...
        'calibrated-path-asymmetry-bias'), ...
    'Path asymmetry must remain a truth-only hardware limit.');

broken = model(100000,120,800,800,4000,1,1,0);
assert(isequal(broken.hardwareEstimatedClockOffsetNs,150 * ones(1,8)) && ...
    isequal(broken.hardwareEstimatedRoundTripDelayNs,1740 * ones(1,8)), ...
    'Omitted calibration must retain the exact stable bias fixture.');
assert(broken.hardwareOffsetPeakToPeakNs == 0 && ...
    broken.hardwareMaxAbsClockOffsetErrorNs == 30 && ...
    broken.hardwareRoundTripPeakToPeakNs == 0 && ...
    broken.hardwareMaxAbsRoundTripErrorNs == 140 && ...
    ~broken.hardwareCalibrationMatched && ...
    strcmp(broken.hardwareState,'miscalibrated-reference-plane'), ...
    'The broken case must be precise-looking, inaccurate, and classified.');
assert(isequal(broken.hardwareCalibrationResidualNs(:,1), ...
        [-20;80;-20;20]) && ...
    all(broken.hardwareQuantizationErrorNs(:) == 0) && ...
    all(broken.hardwareOffsetIdentityResidualNs == 0) && ...
    all(broken.hardwareRoundTripIdentityResidualNs == 0), ...
    'Broken calibration bias must follow the visible placement identity.');
overcorrected = model(100000,120,800,800,4000,1,1,2);
assert(all(overcorrected.hardwareEstimatedClockOffsetNs == 90) && ...
    all(overcorrected.hardwareEstimatedRoundTripDelayNs == 1460) && ...
    all(overcorrected.hardwareClockOffsetErrorNs == -30) && ...
    all(overcorrected.hardwareRoundTripErrorNs == -140), ...
    'Applying twice the correction must flip both calibration-bias signs.');

quantizationTicksNs = [0.125 1 8 64 1024];
for index = 1:numel(quantizationTicksNs)
    swept = model(100000,120,800,800,4000,1, ...
        quantizationTicksNs(index),1);
    assert(max(abs(swept.hardwareQuantizationErrorNs(:))) <= ...
            swept.hardwareQuantizationPerStampBoundNs + ...
            swept.comparisonToleranceNs && ...
        max(abs(swept.hardwareQuantizationOffsetContributionNs)) <= ...
            swept.hardwareQuantizationOffsetBoundNs + ...
            swept.comparisonToleranceNs && ...
        max(abs(swept.hardwareQuantizationRoundTripContributionNs)) <= ...
            swept.hardwareQuantizationRoundTripBoundNs + ...
            swept.comparisonToleranceNs, ...
        'One of the independent quantization bounds was exceeded.');
end

bounded = model(1e6,1e6,1e6,1e6,1e6,4,1024,2);
assert(bounded.exchangeCount == 8 && ...
    bounded.timestampsPerExchange == 4 && ...
    bounded.timestampCount == 32 && bounded.maxTimestampCount == 32 && ...
    all(isfinite(bounded.idealReferencePlaneTimestampNs(:))) && ...
    all(isfinite(bounded.softwareTimestampNs(:))) && ...
    all(isfinite(bounded.hardwareTimestampNs(:))) && ...
    max(abs(bounded.softwareTimestampNs(:))) <= ...
        bounded.maxDerivedTimestampMagnitudeNs && ...
    max(abs(bounded.hardwareTimestampNs(:))) <= ...
        bounded.maxDerivedTimestampMagnitudeNs, ...
    'Maximum valid model inputs must remain finite and fixed-work bounded.');
assert(bounded.maxTimeMagnitudeNs == 1e6 && ...
    bounded.maxHostLatencyScale == 4 && ...
    bounded.minimumHardwareTickNs == 0.125 && ...
    bounded.maxHardwareTickNs == 1024 && ...
    bounded.maxCalibrationFraction == 2 && bounded.calculationBounded, ...
    'Declared input and resource bounds changed.');
assert(all(abs(bounded.idealOffsetIdentityResidualNs) <= ...
        bounded.comparisonToleranceNs) && ...
    all(abs(bounded.softwareOffsetIdentityResidualNs) <= ...
        bounded.comparisonToleranceNs) && ...
    all(abs(bounded.hardwareOffsetIdentityResidualNs) <= ...
        bounded.comparisonToleranceNs) && ...
    all(abs(bounded.hardwareRoundTripIdentityResidualNs) <= ...
        bounded.comparisonToleranceNs), ...
    'Maximum-magnitude identities exceeded the declared tolerance.');
boundedNegative = model(-1e6,-1e6,1e6,1e6,1e6,4,1024,2);
assert(all(isfinite(boundedNegative.softwareTimestampNs(:))) && ...
    all(isfinite(boundedNegative.hardwareTimestampNs(:))) && ...
    max(abs(boundedNegative.hardwareTimestampNs(:))) <= ...
        boundedNegative.maxDerivedTimestampMagnitudeNs, ...
    'Negative time-origin and offset bounds must remain finite.');

assert(baseline.pathSymmetryRequiredForUnbiasedOffset && ...
    baseline.consistentReferencePlaneRequired && ...
    baseline.precisionDoesNotProveAccuracy && ...
    baseline.truthAvailableForTeachingOnly && baseline.leaderClockIsReference && ...
    baseline.sameClockRateAssumed, ...
    'The physical interpretation boundary changed.');
assert(baseline.softwareTimestampPlacementModeled && ...
    baseline.hardwareTimestampPlacementModeled && ...
    baseline.roundToNearestQuantizerIsTeachingChoice && ...
    baseline.simplifiedPtpEventSequenceModeled && ...
    ~baseline.fullPtpProtocolModeled && ...
    ~baseline.oneStepOrTwoStepMessagingModeled && ...
    ~baseline.transparentClockCorrectionModeled && ...
    ~baseline.timestampCorrelationModeled, ...
    'The PTP and quantizer abstraction boundary changed.');
assert(~baseline.clockSkewModeled && ~baseline.clockServoModeled && ...
    ~baseline.packetLossModeled && ~baseline.networkIoPerformed && ...
    ~baseline.physicalHardwareUsed && ~baseline.phcReadPerformed && ...
    ~baseline.clockAdjustmentPerformed && ~baseline.timeoutModeled && ...
    ~baseline.cancellationModeled && ~baseline.actualWaitPerformed, ...
    'The runtime, hardware, clock, timeout, or cancellation boundary changed.');

assertThrows(@() model([],120,800,800,4000,1,8,1), ...
    'P07:InvalidStartTime');
assertThrows(@() model('100000',120,800,800,4000,1,8,1), ...
    'P07:InvalidStartTime');
assertThrows(@() model([100000 100001],120,800,800,4000,1,8,1), ...
    'P07:InvalidStartTime');
assertThrows(@() model(100000 + 1i,120,800,800,4000,1,8,1), ...
    'P07:InvalidStartTime');
assertThrows(@() model(NaN,120,800,800,4000,1,8,1), ...
    'P07:InvalidStartTime');
assertThrows(@() model(Inf,120,800,800,4000,1,8,1), ...
    'P07:InvalidStartTime');
assertThrows(@() model(1e6 + 1,120,800,800,4000,1,8,1), ...
    'P07:InvalidStartTime');
assertThrows(@() model(-1e6 - 1,120,800,800,4000,1,8,1), ...
    'P07:InvalidStartTime');

assertThrows(@() model(100000,[],800,800,4000,1,8,1), ...
    'P07:InvalidClockOffset');
assertThrows(@() model(100000,'120',800,800,4000,1,8,1), ...
    'P07:InvalidClockOffset');
assertThrows(@() model(100000,[120 121],800,800,4000,1,8,1), ...
    'P07:InvalidClockOffset');
assertThrows(@() model(100000,120 + 1i,800,800,4000,1,8,1), ...
    'P07:InvalidClockOffset');
assertThrows(@() model(100000,NaN,800,800,4000,1,8,1), ...
    'P07:InvalidClockOffset');
assertThrows(@() model(100000,Inf,800,800,4000,1,8,1), ...
    'P07:InvalidClockOffset');
assertThrows(@() model(100000,1e6 + 1,800,800,4000,1,8,1), ...
    'P07:InvalidClockOffset');
assertThrows(@() model(100000,-1e6 - 1,800,800,4000,1,8,1), ...
    'P07:InvalidClockOffset');

assertThrows(@() model(100000,120,[],800,4000,1,8,1), ...
    'P07:InvalidForwardDelay');
assertThrows(@() model(100000,120,'800',800,4000,1,8,1), ...
    'P07:InvalidForwardDelay');
assertThrows(@() model(100000,120,[800 801],800,4000,1,8,1), ...
    'P07:InvalidForwardDelay');
assertThrows(@() model(100000,120,800 + 1i,800,4000,1,8,1), ...
    'P07:InvalidForwardDelay');
assertThrows(@() model(100000,120,NaN,800,4000,1,8,1), ...
    'P07:InvalidForwardDelay');
assertThrows(@() model(100000,120,Inf,800,4000,1,8,1), ...
    'P07:InvalidForwardDelay');
assertThrows(@() model(100000,120,-1,800,4000,1,8,1), ...
    'P07:InvalidForwardDelay');
assertThrows(@() model(100000,120,1e6 + 1,800,4000,1,8,1), ...
    'P07:InvalidForwardDelay');

assertThrows(@() model(100000,120,800,[],4000,1,8,1), ...
    'P07:InvalidReverseDelay');
assertThrows(@() model(100000,120,800,'800',4000,1,8,1), ...
    'P07:InvalidReverseDelay');
assertThrows(@() model(100000,120,800,[800 801],4000,1,8,1), ...
    'P07:InvalidReverseDelay');
assertThrows(@() model(100000,120,800,800 + 1i,4000,1,8,1), ...
    'P07:InvalidReverseDelay');
assertThrows(@() model(100000,120,800,NaN,4000,1,8,1), ...
    'P07:InvalidReverseDelay');
assertThrows(@() model(100000,120,800,Inf,4000,1,8,1), ...
    'P07:InvalidReverseDelay');
assertThrows(@() model(100000,120,800,-1,4000,1,8,1), ...
    'P07:InvalidReverseDelay');
assertThrows(@() model(100000,120,800,1e6 + 1,4000,1,8,1), ...
    'P07:InvalidReverseDelay');

assertThrows(@() model(100000,120,800,800,[],1,8,1), ...
    'P07:InvalidFollowerTurnaround');
assertThrows(@() model(100000,120,800,800,'4000',1,8,1), ...
    'P07:InvalidFollowerTurnaround');
assertThrows(@() model(100000,120,800,800,[4000 4001],1,8,1), ...
    'P07:InvalidFollowerTurnaround');
assertThrows(@() model(100000,120,800,800,4000 + 1i,1,8,1), ...
    'P07:InvalidFollowerTurnaround');
assertThrows(@() model(100000,120,800,800,NaN,1,8,1), ...
    'P07:InvalidFollowerTurnaround');
assertThrows(@() model(100000,120,800,800,Inf,1,8,1), ...
    'P07:InvalidFollowerTurnaround');
assertThrows(@() model(100000,120,800,800,-1,1,8,1), ...
    'P07:InvalidFollowerTurnaround');
assertThrows(@() model(100000,120,800,800,1e6 + 1,1,8,1), ...
    'P07:InvalidFollowerTurnaround');

assertThrows(@() model(100000,120,800,800,4000,[],8,1), ...
    'P07:InvalidHostLatencyScale');
assertThrows(@() model(100000,120,800,800,4000,'1',8,1), ...
    'P07:InvalidHostLatencyScale');
assertThrows(@() model(100000,120,800,800,4000,[1 2],8,1), ...
    'P07:InvalidHostLatencyScale');
assertThrows(@() model(100000,120,800,800,4000,1 + 1i,8,1), ...
    'P07:InvalidHostLatencyScale');
assertThrows(@() model(100000,120,800,800,4000,NaN,8,1), ...
    'P07:InvalidHostLatencyScale');
assertThrows(@() model(100000,120,800,800,4000,Inf,8,1), ...
    'P07:InvalidHostLatencyScale');
assertThrows(@() model(100000,120,800,800,4000,-0.1,8,1), ...
    'P07:InvalidHostLatencyScale');
assertThrows(@() model(100000,120,800,800,4000,4.1,8,1), ...
    'P07:InvalidHostLatencyScale');

assertThrows(@() model(100000,120,800,800,4000,1,[],1), ...
    'P07:InvalidHardwareTick');
assertThrows(@() model(100000,120,800,800,4000,1,'8',1), ...
    'P07:InvalidHardwareTick');
assertThrows(@() model(100000,120,800,800,4000,1,[8 16],1), ...
    'P07:InvalidHardwareTick');
assertThrows(@() model(100000,120,800,800,4000,1,8 + 1i,1), ...
    'P07:InvalidHardwareTick');
assertThrows(@() model(100000,120,800,800,4000,1,NaN,1), ...
    'P07:InvalidHardwareTick');
assertThrows(@() model(100000,120,800,800,4000,1,Inf,1), ...
    'P07:InvalidHardwareTick');
assertThrows(@() model(100000,120,800,800,4000,1,0,1), ...
    'P07:InvalidHardwareTick');
assertThrows(@() model(100000,120,800,800,4000,1,0.124,1), ...
    'P07:InvalidHardwareTick');
assertThrows(@() model(100000,120,800,800,4000,1,1025,1), ...
    'P07:InvalidHardwareTick');

assertThrows(@() model(100000,120,800,800,4000,1,8,[]), ...
    'P07:InvalidCalibrationFraction');
assertThrows(@() model(100000,120,800,800,4000,1,8,'1'), ...
    'P07:InvalidCalibrationFraction');
assertThrows(@() model(100000,120,800,800,4000,1,8,[1 2]), ...
    'P07:InvalidCalibrationFraction');
assertThrows(@() model(100000,120,800,800,4000,1,8,1 + 1i), ...
    'P07:InvalidCalibrationFraction');
assertThrows(@() model(100000,120,800,800,4000,1,8,NaN), ...
    'P07:InvalidCalibrationFraction');
assertThrows(@() model(100000,120,800,800,4000,1,8,Inf), ...
    'P07:InvalidCalibrationFraction');
assertThrows(@() model(100000,120,800,800,4000,1,8,-0.1), ...
    'P07:InvalidCalibrationFraction');
assertThrows(@() model(100000,120,800,800,4000,1,8,2.1), ...
    'P07:InvalidCalibrationFraction');

recovered = model(100000,120,800,800,4000,1,8,1);
assert(isequal(recovered.trueEventTimeNs,baseline.trueEventTimeNs) && ...
    isequal(recovered.softwareTimestampNs,baseline.softwareTimestampNs) && ...
    isequal(recovered.hardwareTimestampNs,baseline.hardwareTimestampNs) && ...
    isequal(recovered.softwareEstimatedClockOffsetNs, ...
        baseline.softwareEstimatedClockOffsetNs) && ...
    isequal(recovered.hardwareEstimatedClockOffsetNs, ...
        baseline.hardwareEstimatedClockOffsetNs), ...
    'A valid call after malformed inputs must recover with no retained state.');

disp(['P07 checks passed: capture-plane equations, deterministic baseline, two sweeps, ' ...
    'broken calibration, asymmetry limit, malformed inputs, bounds, and recovery.']);
end

function assertThrows(action,expectedIdentifier)
didThrow = false;
try
    action();
catch exception
    didThrow = true;
    assert(strcmp(exception.identifier,expectedIdentifier), ...
        'Expected %s but received %s.',expectedIdentifier,exception.identifier);
end
assert(didThrow,'Expected error %s was not thrown.',expectedIdentifier);
end
